/**
 * Auto-generated by scripts/inline-html.js
 * DO NOT EDIT — changes to public/index.html will be overwritten
 */
const HTML = `<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- 系统字体，无需外部加载 -->
<title>SUB-Aggregation</title>
<style>
:root, [data-theme="light"] {
  --bg: #fafbfc; --bg2: #ffffff; --bg3: #f4f6f9;
  --border: #e8edf2; --text: #0a1e35; --text2: #5a6c80;
  --accent: #533afd; --accent-hover: #4434d4; --accent2: #533afd;
  --accent-soft: rgba(83,58,253,0.06); --accent-soft-d: rgba(124,104,255,0.12);
  --green: #108c3d; --red: #ea2261; --orange: #9b6829;
  --shadow: 0 1px 3px rgba(23,23,23,0.04), 0 8px 24px -8px rgba(23,23,23,0.08);
  --shadow-sm: 0 1px 2px rgba(23,23,23,0.04), 0 1px 4px rgba(23,23,23,0.04);
  --shadow-brand: 0 20px 50px -20px rgba(83,58,253,0.25), 0 8px 24px -12px rgba(0,0,0,0.08);
  --side-bg: #f4f6f9;
  --radius: 8px; --radius-sm: 5px; --radius-lg: 12px;
}
[data-theme="dark"] {
  --bg: #0a0e14; --bg2: #131820; --bg3: #1a212b;
  --border: #252e3a; --text: #e6edf3; --text2: #7d8a9e;
  --accent: #7c68ff; --accent-hover: #9484ff; --accent2: #7c68ff;
  --accent-soft: rgba(124,104,255,0.08); --accent-soft-d: rgba(124,104,255,0.14);
  --green: #3fb950; --red: #f8517c; --orange: #d29922;
  --shadow: 0 1px 3px rgba(0,0,0,0.2), 0 8px 24px -8px rgba(0,0,0,0.35);
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.15), 0 1px 4px rgba(0,0,0,0.15);
  --shadow-brand: 0 20px 50px -20px rgba(124,104,255,0.2), 0 8px 24px -12px rgba(0,0,0,0.3);
  --side-bg: #0d1219;
  --radius: 8px; --radius-sm: 5px; --radius-lg: 12px;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif;
  background: var(--bg); color: var(--text);
  font-size: 18px; line-height: 1.5; font-weight: 400;
  letter-spacing: -0.011em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
/* ===== Sidebar Layout ===== */
.app-shell { display: flex; min-height: 100vh; max-width: 1400px; margin: 0 auto; width: 100%; }
.sidebar {
  width: 208px; flex-shrink: 0;
  background: var(--side-bg); border-right: 1px solid var(--border);
  padding: 18px 12px; display: flex; flex-direction: column; gap: 2px;
  position: sticky; top: 0; height: 100vh; overflow-y: auto;
}
.sidebar .logo {
  font-weight: 600; font-size: 19px; letter-spacing: -0.02em;
  color: var(--text); padding: 2px 10px 16px;
}
.sidebar .logo span { color: var(--accent); }
.sgroup { font-size: 12px; color: var(--text2); letter-spacing: .08em; text-transform: uppercase; padding: 14px 10px 5px; font-weight: 600; }
.nav-tab {
  display: flex; align-items: center; gap: 9px;
  padding: 8px 16px; cursor: pointer;
  color: var(--text2); border-radius: var(--radius-sm);
  font-size: 16px; font-weight: 500; white-space: nowrap;
  letter-spacing: -0.01em;
  transition: all .2s cubic-bezier(0.16, 1, 0.3, 1);
}
.nav-tab:hover { color: var(--accent); background: var(--accent-soft); }
[data-theme="dark"] .nav-tab:hover { background: var(--accent-soft-d); }
.nav-tab.active { color: #fff; background: var(--accent); font-weight: 600; box-shadow: 0 2px 8px rgba(83,58,253,0.25); }
[data-theme="dark"] .nav-tab.active { color: #fff; box-shadow: 0 2px 8px rgba(124,104,255,0.2); }
.sidebar-footer { margin-top: auto; padding-top: 14px; display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.main-col { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  padding: 7px 15px; border-radius: var(--radius-sm);
  border: 1px solid var(--border);
  background: var(--bg2); color: var(--text);
  cursor: pointer; font-size: 16px; font-weight: 500;
  letter-spacing: -0.01em;
  transition: all .15s cubic-bezier(0.16, 1, 0.3, 1);
}
.btn:hover { border-color: var(--accent); color: var(--accent); }
.btn:active { transform: scale(0.97); }
.btn-primary { background: var(--accent); color: #fff; border-color: var(--accent); }
.btn-primary:hover { background: var(--accent-hover); color: #fff; }
.btn-danger { color: var(--red); border-color: rgba(234,34,97,0.3); }
.btn-danger:hover { background: var(--red); color: #fff; border-color: var(--red); }
.btn-sm { padding: 4px 11px; font-size: 14px; }
.node-lock-btn { padding: 3px 7px; line-height: 1; background: transparent; border: 1px solid var(--border); color: var(--text2); }
.node-lock-on { background: var(--text); color: var(--bg); border-color: var(--text); font-weight: 700; }
/* ===== Page ===== */
.page { display: none; padding: 28px 32px; max-width: 1060px; width: 100%; margin: 0 auto; }
.page.active { display: block; animation: fadeUp .3s cubic-bezier(0.16, 1, 0.3, 1); }
@keyframes fadeUp { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }
.page h2 { font-size: 24px; font-weight: 600; letter-spacing: -0.02em; line-height: 1.2; margin-bottom: 20px; }
/* ===== Cards ===== */
.card {
  background: var(--bg2); border-radius: var(--radius);
  padding: 20px; margin-bottom: 14px;
  border: 1px solid var(--border);
  box-shadow: var(--shadow-sm);
  transition: box-shadow .2s ease;
}
.card:hover { box-shadow: var(--shadow); }
.card-title { font-size: 12px; color: var(--text2); margin-bottom: 6px; font-weight: 600; letter-spacing: .06em; text-transform: uppercase; }
.card-value { font-size: 28px; font-weight: 400; letter-spacing: -0.02em; line-height: 1.15; font-feature-settings: 'tnum'; }
/* ===== Stats Grid ===== */
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 14px; margin-bottom: 28px; }
.card-sub { font-size: 12px; color: var(--text2); margin-top: 4px; }
/* ===== Forms ===== */
input, select {
  padding: 10px 14px; border: 1px solid var(--border);
  border-radius: var(--radius-sm); background: var(--bg2); color: var(--text);
  font-size: 17px; width: 100%; font-family: inherit;
  letter-spacing: -0.01em;
  transition: all .2s cubic-bezier(0.16, 1, 0.3, 1);
}
input:focus, select:focus {
  outline: none; border-color: var(--accent2);
  box-shadow: 0 0 0 3px var(--accent-soft);
}
.form-group { margin-bottom: 14px; }
.form-group label { display: block; font-size: 14px; color: var(--text2); margin-bottom: 6px; font-weight: 500; letter-spacing: 0; }
.form-row { display: flex; gap: 12px; align-items: flex-end; }
.form-row .form-group { flex: 1; }
/* ===== Tables ===== */
table { width: 100%; border-collapse: collapse; }
th, td { padding: 11px 10px; text-align: left; border-bottom: 1px solid var(--border); font-size: 16px; }
th { color: var(--text2); font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
tbody tr { transition: background .15s; }
tbody tr:hover { background: var(--accent-soft); }
[data-theme="dark"] tbody tr:hover { background: var(--accent-soft-d); }
/* ===== Tags ===== */
.tag { display: inline-block; padding: 2px 8px; border-radius: 980px; font-size: 13px; font-weight: 600; letter-spacing: 0; }
.tag-vmess { background: #e8f4ff; color: #0071e3; }
.tag-vless { background: #e3f7ec; color: #1a8f4a; }
.tag-trojan { background: #fff1e5; color: #bd561d; }
.tag-ss { background: #f3e8ff; color: #8250df; }
[data-theme="dark"] .tag-vmess { background: rgba(13,75,188,0.25); color: #7fb0ff; }
[data-theme="dark"] .tag-vless { background: rgba(29,145,89,0.2); color: #4fd183; }
[data-theme="dark"] .tag-trojan { background: rgba(189,86,29,0.2); color: #ffa657; }
[data-theme="dark"] .tag-ss { background: rgba(130,80,223,0.2); color: #d2a8ff; }
.tag-ssr { background: #ffe8ef; color: #c2255c; }
.tag-hysteria2 { background: #e0f7fa; color: #0891b2; }
.tag-tuic { background: #fff8e1; color: #b45309; }
.tag-wireguard { background: #e0e7ff; color: #4338ca; }
.tag-anytls { background: #fce7f3; color: #be185d; }
.tag-other { background: #f1f5f9; color: #475569; }
[data-theme="dark"] .tag-ssr { background: rgba(194,37,92,0.2); color: #ff7aa2; }
[data-theme="dark"] .tag-hysteria2 { background: rgba(8,145,178,0.2); color: #67e8f9; }
[data-theme="dark"] .tag-tuic { background: rgba(180,83,9,0.2); color: #fbbf24; }
[data-theme="dark"] .tag-wireguard { background: rgba(67,56,202,0.2); color: #a5b4fc; }
[data-theme="dark"] .tag-anytls { background: rgba(190,24,93,0.2); color: #f9a8d4; }
[data-theme="dark"] .tag-other { background: rgba(71,85,105,0.25); color: #94a3b8; }
/* ===== Status ===== */
.status-active { color: var(--green); }
.status-error { color: var(--red); }
.status-disabled { color: var(--text2); }
/* ===== Modal ===== */
.modal-overlay {
  display: none; position: fixed; inset: 0;
  background: rgba(0,0,0,0.35);
  backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);
  z-index: 9999; align-items: center; justify-content: center;
}
.modal-overlay.show { display: flex; animation: fadeUp .25s cubic-bezier(0.16, 1, 0.3, 1); }
.modal-content {
  background: var(--bg2); border-radius: var(--radius-lg);
  width: 90%; max-width: 700px; max-height: 90vh; overflow: auto;
  box-shadow: 0 24px 70px rgba(0,0,0,0.18);
}
.modal-header { padding: 18px 24px; border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; }
.modal-header h3 { font-size: 18px; font-weight: 600; letter-spacing: -0.02em; }
.modal-body { padding: 24px; }
.modal-close {
  cursor: pointer; font-size: 18px; color: var(--text2);
  background: none; border: none; width: 28px; height: 28px;
  border-radius: 50%; display: flex; align-items: center; justify-content: center;
  transition: all .2s;
}
.modal-close:hover { color: var(--text); background: var(--bg3); }
/* ===== Sub Items ===== */
.sub-item {
  display: flex; align-items: center; gap: 12px;
  padding: 14px 16px; border-radius: var(--radius);
  margin-bottom: 8px; cursor: pointer;
  background: var(--bg2); box-shadow: var(--shadow-sm); border: 1px solid var(--border);
  transition: all .2s cubic-bezier(0.16, 1, 0.3, 1);
}
.sub-item:hover { transform: translateY(-1px); box-shadow: var(--shadow); border-color: var(--accent); }
.sub-item .name { font-weight: 600; min-width: 120px; font-size: 16px; }
.sub-item .desc { color: var(--text2); font-size: 14px; min-width: 150px; }
.sub-item input { flex: 1; font-size: 14px; padding: 6px 10px; border: none; border-radius: var(--radius-sm); background: var(--bg3); color: var(--text); }
.sub-group-label {
  font-size: 13px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;
  color: var(--text2); margin: 18px 0 8px; padding: 0 4px;
  border-bottom: 1px solid var(--border); line-height: 1;
}
.sub-group-label:first-child { margin-top: 0; }
/* ===== Login ===== */
.login-page { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; position: relative; overflow: hidden; background: linear-gradient(135deg, #0a0e35 0%, #2e2b8c 50%, #533afd 100%); }
.login-page::before { content:''; position:absolute; width:480px; height:480px; border-radius:50%; background:radial-gradient(circle,rgba(249,107,238,0.18),transparent 70%); top:-160px; right:-100px; }
.login-page::after { content:''; position:absolute; width:400px; height:400px; border-radius:50%; background:radial-gradient(circle,rgba(234,34,97,0.15),transparent 70%); bottom:-140px; left:-80px; }
.login-card {
  position: relative; z-index: 1;
  background: var(--bg2); border-radius: var(--radius-lg);
  padding: 40px 36px; width: 100%; max-width: 380px;
  box-shadow: var(--shadow-brand); animation: fadeUp .4s cubic-bezier(0.16, 1, 0.3, 1);
  border: 1px solid rgba(255,255,255,0.08);
}
.login-card h1 { text-align: center; margin-bottom: 26px; font-size: 28px; font-weight: 300; letter-spacing: -0.02em; }
.login-footer { display: flex; align-items: center; justify-content: center; gap: 8px; margin-top: 22px; font-size: 14px; color: var(--text2); }
.login-footer a, .app-footer a { color: var(--accent); text-decoration: none; }
.login-footer a:hover, .app-footer a:hover { text-decoration: underline; }
.dot { opacity: 0.4; }
.app-footer { border-top: 1px solid var(--border); margin-top: 32px; padding: 16px 4px; font-size: 14px; color: var(--text2); }
/* ===== Upgrade Banner ===== */
.upgrade-banner { display: inline-flex; align-items: center; gap: 6px; padding: 3px 12px; border-radius: 20px; font-size: 14px; font-weight: 600; background: #fff8e1; color: #b45309; }
.upgrade-banner a { color: #b45309; text-decoration: none; }
.upgrade-banner a:hover { text-decoration: underline; }
/* ===== Toast ===== */
.toast { position: fixed; bottom: 24px; right: 24px; z-index: 99999; padding: 12px 20px; border-radius: var(--radius); color: #fff; font-size: 16px; font-weight: 500; max-width: 360px; animation: fadeIn .3s; box-shadow: 0 8px 30px rgba(0,0,0,0.2); }
.toast-success { background: #1d9159; }
.toast-error { background: #ff3b30; }
/* ===== Rules Tree ===== */
.rules-group { background: var(--bg2); border-radius: var(--radius); margin-bottom: 8px; border: 1px solid var(--border); box-shadow: var(--shadow-sm); overflow: hidden; }
.rules-loading { padding: 40px 20px; text-align: center; color: var(--text2); }
.rules-group-head { display: flex; align-items: center; gap: 10px; padding: 14px 16px; cursor: pointer; user-select: none; transition: background .2s; }
.rules-group-head:hover { background: var(--accent-soft); }
[data-theme="dark"] .rules-group-head:hover { background: var(--accent-soft-d); }
.rules-arrow { display: inline-flex; transition: transform .25s cubic-bezier(0.16, 1, 0.3, 1); color: var(--text2); font-size: 12px; width: 14px; justify-content: center; }
.rules-group-head.open .rules-arrow { transform: rotate(90deg); }
.rules-group-title { font-weight: 600; font-size: 17px; flex: 1; }
/* 序号徽章：组顺序 = 输出匹配顺序（先命中生效），把隐含的排序显式化 */
.rules-group-index { display: inline-flex; align-items: center; justify-content: center; min-width: 22px; height: 22px; padding: 0 6px; margin-right: 8px; border-radius: 6px; background: var(--accent-soft); color: var(--accent); font-size: 13px; font-weight: 700; }
[data-theme="dark"] .rules-group-index { background: var(--accent-soft-d); }
.rules-group-count { font-size: 14px; color: var(--text2); background: var(--bg3); padding: 2px 10px; border-radius: 999px; }
[data-theme="dark"] .rules-group-count { background: var(--bg3); }
.rules-items { display: none; padding: 6px 20px 16px 48px; gap: 8px 14px; }
.rules-group-head.open + .rules-items { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }
/* v2.27.0 锁死模型：内置规则锁死（只整组开关），自定义规则可逐条 */
.rules-locked { display: flex; align-items: center; gap: 9px; cursor: default; opacity: .9; }
.rules-lock-icon { flex: none; font-size: 14px; width: 20px; text-align: center; opacity: .85; }
.rules-custom { cursor: pointer; }
.rules-off { opacity: .45; padding: 9px 12px; border-radius: 10px; }
.rules-group-off .rules-group-head { opacity: .55; }
.rules-item {
  display: grid;
  grid-template-columns: 20px 1fr;
  align-items: center;
  gap: 9px;
  padding: 9px 12px; border-radius: 10px;
  cursor: pointer; font-size: 13px;
  min-width: 0; line-height: 1.3;
  height: 48px;
}
.rules-item .rule-label {
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  min-width: 0;
}
.rules-item .rule-main {
  display: grid;
  gap: 2px;
  min-width: 0;
  flex: 1;
}
.rules-item .rule-name {
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.rules-item .rule-id {
  font-size: 13px; color: var(--text2);
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.rules-group-head input[type="checkbox"] { accent-color: var(--accent); cursor: pointer; width: 16px; height: 16px; }
/* ===== Catalog Type Filter Chips ===== */
.catalog-chip {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 6px 14px; border-radius: 980px;
  border: 1px solid var(--border); background: var(--bg2);
  color: var(--text2); font-size: 15px; font-weight: 500;
  cursor: pointer; transition: all .2s cubic-bezier(0.16, 1, 0.3, 1);
}
.catalog-chip:hover { background: var(--bg3); }
.catalog-chip.active { background: var(--accent); color: #fff; border-color: var(--accent); }
.catalog-chip-count { font-size: 13px; background: var(--bg3); padding: 1px 7px; border-radius: 999px; }
.catalog-chip.active .catalog-chip-count { background: rgba(255,255,255,0.22); }
/* ===== Scroll to Top ===== */
.scroll-top { position: fixed; bottom: 60px; right: 20px; z-index: 999; width: 44px; height: 44px; border-radius: 50%; background: var(--accent); color: #fff; border: none; cursor: pointer; font-size: 18px; display: none; box-shadow: var(--shadow-sm); transition: all .2s; }
.scroll-top:hover { background: var(--accent-hover); }
.scroll-top.show { display: flex; align-items: center; justify-content: center; }
/* ===== Helpers ===== */
.text-center { text-align: center; }
.mt-12 { margin-top: 12px; }
.mb-12 { margin-bottom: 12px; }
.gap-8 { gap: 8px; }
.flex { display: flex; }
.flex-wrap { flex-wrap: wrap; }
.items-center { align-items: center; }
/* ===== Responsive ===== */
@media (max-width: 900px) {
  .app-shell { flex-direction: column; }
  .sidebar { width: 100%; height: auto; position: static; flex-direction: row; align-items: center; overflow-x: auto; padding: 10px 14px; gap: 4px; }
  .sidebar .logo { padding: 0 8px 0 0; white-space: nowrap; }
  .sgroup { display: none; }
  .nav-tab { white-space: nowrap; }
  .sidebar-footer { margin-top: 0; margin-left: auto; padding-top: 0; }
  .page { padding: 20px 14px; }
  .stats-grid { grid-template-columns: 1fr 1fr; gap: 10px; }
  .sub-item { flex-wrap: wrap; padding: 12px; }
  .sub-item input { min-width: 100%; }
  .sub-item .name { min-width: 100%; }
  .form-row { flex-direction: column; }
}
</style>
</head>
<body>
<div id="app" style="display:none">
  <div class="app-shell">
    <aside class="sidebar">
      <div class="logo" id="sidebarLogo">◆ SUB<span>Next</span></div>
      <div class="sgroup">总览</div>
      <div class="nav-tab active" data-page="dashboard" onclick="switchPage('dashboard')">📊 仪表盘</div>
      <div class="sgroup">资源</div>
      <div class="nav-tab" data-page="subscribe" onclick="switchPage('subscribe')">📥 订阅管理</div>
      <div class="nav-tab" data-page="nodes" onclick="switchPage('nodes')">🔗 节点列表</div>
      <div class="nav-tab" data-page="rules" onclick="switchPage('rules')">🌐 分流规则</div>
      <div class="sgroup">发布</div>
      <div class="nav-tab" data-page="output" onclick="switchPage('output')">📦 输出配置</div>
      <div class="nav-tab" data-page="settings" onclick="switchPage('settings')">⚙️ 设置</div>
      <div class="sidebar-footer">
        <button class="btn btn-sm" onclick="cycleTheme()" id="themeBtn">🌙</button>
        <span id="userBadge" style="font-size:12.5px;color:var(--text2)">admin</span>
        <button class="btn btn-sm" onclick="logout()">🚪 退出</button>
        <div class="sidebar-version" style="margin-top:12px;padding-top:12px;border-top:1px solid var(--border);font-size:14px;color:var(--text2);display:flex;flex-direction:column;gap:4px;align-items:center">
          <span>SUB-Aggregation v<span id="appVersion">-</span></span>
          <a href="https://github.com/bobvane/SUB-Aggregation" target="_blank" rel="noopener" style="color:var(--accent);text-decoration:none">GitHub</a>
          <span id="upgradeStatusSidebar" style="font-size:14px"></span>
        </div>
      </div>
    </aside>
    <div class="main-col">

  <!-- Dashboard -->
  <div class="page active" id="page-dashboard">
    <h2 style="margin-bottom:16px">📊 仪表盘</h2>
    <div class="stats-grid" id="statsGrid">
      <div class="card"><div class="card-title">订阅数量</div><div class="card-value" id="statSubs">-</div></div>
      <div class="card"><div class="card-title">已启用订阅</div><div class="card-value" id="statEnabledSubs">-</div></div>
      <div class="card"><div class="card-title">已禁用订阅</div><div class="card-value" id="statDisabledSubs">-</div></div>
      <div class="card"><div class="card-title">节点总数</div><div class="card-value" id="statNodes">-</div><div class="card-sub" id="statNodesSub"></div></div>
      <div class="card"><div class="card-title">🟢 存活</div><div class="card-value" id="statAlive" style="color:var(--success)">-</div></div>
      <div class="card"><div class="card-title">🔴 不通</div><div class="card-value" id="statDead" style="color:var(--danger)">-</div></div>
      <div class="card"><div class="card-title">🚫 已抛弃</div><div class="card-value" id="statDropped" style="color:var(--danger)">-</div></div>
      <div class="card"><div class="card-title">🕒 上次测活</div><div class="card-value" style="font-size:14px" id="statLastProbe">未测活</div></div>
      <div class="card"><div class="card-title">协议分布</div><div class="card-value" style="font-size:14px" id="statProto">-</div></div>
      <div class="card"><div class="card-title">最近更新</div><div class="card-value" style="font-size:14px" id="statUpdate">-</div></div>
    </div>
    <!-- v2.32: 操作日志「最近动态」卡片 -->
    <div class="card" style="margin-bottom:14px">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px">
        <div class="card-title" style="margin:0">最近动态</div>
        <button class="btn btn-sm btn-danger" onclick="clearOperationLogs()">🗑 清空</button>
      </div>
      <div id="opLogList" style="font-size:14px;color:var(--text2);max-height:220px;overflow-y:auto"></div>
    </div>

  </div>

  <!-- Subscriptions -->
  <div class="page" id="page-subscribe">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
      <h2>📥 订阅管理</h2>
      <button class="btn btn-primary" onclick="showAddSub()">＋ 添加订阅</button>
    </div>
    <table id="subTable">
      <thead><tr><th>名称</th><th>链接</th><th>状态</th><th>节点数</th><th>更新时间</th><th>操作</th></tr></thead>
      <tbody id="subTableBody"></tbody>
    </table>
  </div>

  <!-- Nodes -->
  <div class="page" id="page-nodes">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
      <h2>🔗 节点列表</h2>
      <div style="display:flex;gap:8px;align-items:center">
        <input style="width:auto;max-width:300px" placeholder="🔍 搜索节点名或地址..." id="nodeSearch" oninput="filterNodes()">
        <button class="btn btn-sm btn-primary" onclick="probeAllNodes()" title="对所有节点执行 TCP/TLS/HTTP 测活">⚡ 立即测活</button>
      </div>
    </div>
    <div class="card" style="padding:12px 16px;font-size:14px;color:var(--text2)">
      💡 勾选 = 该节点会进入输出配置；取消勾选 = 从输出的订阅中排除。测速请在客户端（OpenClash/Mihomo 等）导入订阅后测试。
    </div>
    <div class="card" id="nodeStats" style="margin:12px 0;padding:10px 16px;display:flex;gap:24px;font-size:14px;flex-wrap:wrap;align-items:center">
      <span>📥 总节点 <b id="statsOriginal">0</b></span>
      <span>🔀 重复 <b id="statsDuplicates">0</b></span>
      <span>✅ 实际 <b id="statsUnique">0</b></span>
      <span >🌐 未识别国家码 <b id="statsGeoUnlocated" style="color:var(--danger)">0</b></span>
      <span>🟢 存活 <b id="statsAlive" style="color:var(--success)">0</b></span>
      <span>🔴 不通 <b id="statsDead" style="color:var(--danger)">0</b></span>
      <span>🚫 已抛弃 <b id="statsDropped" style="color:var(--danger)">0</b></span>
      <span>🕒 上次测活 <b id="statsLastProbe">未测活</b></span>
      <span style="color:var(--text2)">（去重依据：IP + 端口 + 协议）</span>
      <span style="margin-left:auto">
        <button class="btn btn-sm" onclick="redetectGeo()">🔄 重新检测国家码</button>
      </span>
    </div>
    <div id="geoPendingBanner" class="card" style="display:none;margin:0 0 12px;padding:10px 16px;font-size:14px;border-left:4px solid var(--danger);box-shadow:var(--shadow-sm)"></div>
    <div class="card" style="margin:0 0 12px;padding:10px 16px;font-size:14px;display:flex;gap:8px;align-items:center">
      <span>🏷 节点名自动生成</span>
      <span style="color:var(--text2)">格式：旗帜 国家码 协议-序号（如 🇭🇰 HK VLESS-01），无需手工清洗；延迟见「延迟」列，不写进名字</span>
    </div>
    <table id="nodesTable">
      <thead><tr><th style="width:40px" title="锁定后无视测活/延迟，强制进配置">锁定</th><th>名称</th><th>协议</th><th>地址</th><th>端口</th><th>TLS</th><th style="cursor:pointer;user-select:none" onclick="sortNodesByLatency()" title="点击切换延迟排序">延迟 <span id="latencySortMark"></span></th><th>状态</th><th>操作</th></tr></thead>
      <tbody id="nodesTableBody"></tbody>
    </table>
    <p class="text-center" id="nodesEmpty" style="color:var(--text2);padding:24px">暂无节点数据</p>
  </div>

  <!-- Rules -->
  <div class="page" id="page-rules">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
      <h2>🌐 分流规则</h2>
      <span style="font-size:14px;color:var(--text2)">已开启 <b id="rulesCount" style="color:var(--accent)">0</b> 类规则</span>
    </div>
    <div class="card" style="padding:12px 16px;font-size:14px;color:var(--text2)">
      💡 本页按<b>自上而下的顺序</b>写入分流规则（顺序即匹配优先级，先命中生效）。组内内置规则<b>锁死</b>，只能整组开关；<b>自定义规则</b>可逐条勾选/删除，且排在其所属组的位置。内网防代理与 QUIC 防泄漏为内置最前两层，不在此页展示。
    </div>
    <div class="card" style="padding:12px 16px;margin-bottom:12px">
      <div style="font-size:14px;font-weight:500;margin-bottom:8px">⚡ 快速预设 <span style="color:var(--text2);font-weight:normal;font-size:14px">点击覆盖当前勾选，配置跟随输出</span></div>
      <div style="display:flex;gap:8px;flex-wrap:wrap" id="presetBar"></div>
    </div>
    <div style="display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:16px;align-items:start" id="rulesTwoCol">
      <div>
        <div id="rulesTree"></div>
        <div style="margin-top:12px;display:flex;gap:8px">
          <button class="btn btn-primary" onclick="selectAllRules(true)">✅ 全选</button>
          <button class="btn" onclick="selectAllRules(false)">⬜ 全不选</button>
          <button class="btn" onclick="resetRulesExpanded()">🔽 全部展开</button>
        </div>
      </div>

      <!-- 规则库：从 MetaCubeX 全量分类挑选加入分流规则 + 同步管理（右侧栏） -->
      <div class="card" style="position:sticky;top:16px">
      <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;margin-bottom:12px">
        <h3 style="margin:0">📚 规则库 <span style="color:var(--text2);font-size:14px;font-weight:normal">从 MetaCubeX 分类中挑选加入分流规则</span></h3>
        <div style="display:flex;align-items:center;gap:12px">
          <span style="color:var(--text2);font-size:14px" id="catalogCount"></span>
          <button class="btn btn-sm" onclick="refreshCatalog()" id="catalogRefreshBtn">🔄 立即刷新</button>
        </div>
      </div>
      <!-- 同步状态（失效分类以官方规则库为准自动清理，不保留历史） -->
      <div id="catalogStatus" style="color:var(--text2);font-size:14px;padding:6px 12px;background:var(--bg);border-radius:8px;margin-bottom:12px">加载中…</div>
      <!-- 分类筛选 chips（方案 A：缩小范围再挑，避免平铺几千条） -->
      <div id="catalogTypeFilter" style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px">
        <button class="catalog-chip active" data-type="" onclick="setCatalogType(this)">全部</button>
        <button class="catalog-chip" data-type="aggregate" onclick="setCatalogType(this)">🎯 聚合 <span class="catalog-chip-count" data-count="aggregate">0</span></button>
        <button class="catalog-chip" data-type="site" onclick="setCatalogType(this)">🌐 站点 <span class="catalog-chip-count" data-count="site">0</span></button>
      </div>
      <div class="form-group">
        <input id="catalogSearch" placeholder="🔍 输入分类名或搜索（如 netflix、openai、ads）…" oninput="debouncedSearchCatalog()">
      </div>
      <div id="catalogList" style="max-height:420px;overflow-y:auto;border:1px solid var(--border);border-radius:12px;padding:8px">
        <div style="color:var(--text2);padding:16px;text-align:center">输入关键词开始搜索</div>
      </div>
      </div><!-- /规则库右栏 -->
    </div><!-- /rulesTwoCol -->
  </div>

  <!-- Output -->
  <div class="page" id="page-output">
    <!-- 格式选择器 + 主操作（A：提到主流程） -->
    <div class="card" style="display:flex;flex-wrap:wrap;align-items:flex-end;gap:12px;margin-bottom:16px">
      <div style="flex:1;min-width:220px">
        <label for="outputFormatSelect" style="display:block;font-size:14px;color:var(--text2);margin-bottom:6px;font-weight:500">选择客户端格式</label>
        <select id="outputFormatSelect" onchange="onOutputFormatChange()">
          <option value="mihomo">🐱 Mihomo / Clash / Stash</option>
          <option value="singbox">📦 Sing-box</option>
          <option value="v2ray">📄 V2ray (Base64)</option>
          <option value="v2rayn">📱 V2RayNG</option>
          <option value="nekoray">🪐 NekoRay</option>
          <option value="shadowrocket">🚀 Shadowrocket</option>
        </select>
      </div>
      <div style="display:flex;gap:8px;flex-wrap:wrap">
        <button class="btn btn-primary" onclick="copyOutputFormatUrl()">📋 复制订阅链接</button>
        <button class="btn btn-primary" onclick="downloadOutputFormat()">💾 下载配置文件</button>
        <button class="btn" onclick="showQrOutputFormat()">📱 二维码</button>
        <button class="btn" onclick="previewOutputFormat()">👁️ 预览配置</button>
      </div>
    </div>
    <div id="outputNodeCount" style="font-size:14px;color:var(--text2);margin-bottom:16px">0 个节点</div>
    <div id="outputLinks"></div>
  </div>

  <!-- Settings -->
  <div class="page" id="page-settings">
    <h2 style="margin-bottom:16px">⚙️ 设置</h2>
    <div class="card">
      <div class="form-group">
        <label>系统名称</label>
        <input id="settingAppName" placeholder="SUB-Aggregation">
      </div>
      <div class="form-group">
        <label>订阅自动更新间隔（小时，1-24；0 = 不更新。默认 24）</label>
        <input id="settingSubUpdateInterval" type="number" min="0" max="24" placeholder="24">
        <div class="hint" style="margin-top:6px;color:var(--muted-foreground);font-size:12px">每隔设定的小时数自动拉取全部订阅（按整点判断，实际误差不超过 1 小时）</div>
      </div>
      <div class="form-group">
        <label>慢节点抛弃阈值（毫秒，100-2000；默认 2000）</label>
        <input id="settingNodeDropLatency" type="number" min="100" max="2000" placeholder="2000">
        <div class="hint" style="margin-top:6px;color:var(--muted-foreground);font-size:12px">测活延迟超过该值的节点视为「已抛弃」：不写入生成的配置，节点记录保留、延迟回落后自动恢复</div>
      </div>
      <button class="btn btn-primary mt-12" onclick="saveSettings()">💾 保存</button>
    </div>
    <div class="card" style="margin-top:16px">
      <h3 style="margin:0 0 12px">👤 账号安全</h3>
      <div class="form-group">
        <label>当前用户名：<b id="currentUsername" style="color:var(--accent)">-</b></label>
        <label style="margin-top:8px">新用户名（2-32位字母数字_-）</label>
        <input id="settingNewUsername" placeholder="新用户名" autocomplete="off">
        <label style="margin-top:8px">当前密码（确认）</label>
        <input type="password" id="settingUsernamePassword" autocomplete="current-password">
      </div>
      <button class="btn btn-primary" onclick="changeUsername()">修改用户名</button>
    </div>
    <div class="card" style="margin-top:16px">
      <h3 style="margin:0 0 12px">🔑 修改密码</h3>
      <div class="form-group">
        <label>旧密码</label>
        <input type="password" id="settingOldPassword" autocomplete="current-password">
        <label style="margin-top:8px">新密码（至少6位）</label>
        <input type="password" id="settingNewPassword" autocomplete="new-password">
        <label style="margin-top:8px">确认新密码</label>
        <input type="password" id="settingNewPassword2" autocomplete="new-password">
      </div>
      <button class="btn btn-primary" onclick="changePassword()">修改密码</button>
      <p class="mt-12" style="color:var(--text2);font-size:14px">修改成功后需重新登录。</p>
    </div>
  </div>

  <!-- 加入规则弹窗 -->
  <div class="modal-overlay" id="addRuleModal">
    <div class="modal-content" style="max-width:480px">
      <div class="modal-header"><h3>➕ 加入分流规则</h3><button class="modal-close" onclick="closeModal('addRuleModal')">✕</button></div>
      <div class="modal-body">
        <div class="form-group"><label>分类 ID</label><input id="addRuleId" readonly></div>
        <div class="form-group"><label>显示名称</label><input id="addRuleLabel" placeholder="例如: Netfilx"></div>
        <div class="form-group">
          <label>目标分组</label>
          <select id="addRuleGroup"></select>
        </div>
        <button class="btn btn-primary" style="width:100%;justify-content:center" onclick="confirmAddRule()">✅ 加入规则</button>
      </div>
    </div>
        </div>

      </div><!-- /app-shell -->
    </div>
  </div>

  <!-- Login -->
  <div class="login-page" id="loginPage" style="display:none">
  <div class="login-card">
    <h1 id="loginTitle">🔐 SUB-Aggregation</h1>
    <div class="form-group">
      <label>用户名</label>
      <input id="loginUsername" placeholder="admin" autocomplete="username">
    </div>
    <div class="form-group">
      <label>管理员密码</label>
      <input type="password" id="loginPassword" placeholder="输入密码" autocomplete="current-password" onkeydown="if(event.key==='Enter')login()">
    </div>
    <button class="btn btn-primary" style="width:100%;justify-content:center" onclick="login()">登录</button>
    <p class="text-center mt-12" style="color:var(--text2);font-size:14px">首次登录使用 ADMIN_PASSWORD 环境变量设置的密码</p>
    <!-- 项目品牌信息 -->
    <div class="login-footer">
      <a href="https://github.com/bobvane/SUB-Aggregation" target="_blank" rel="noopener">⭐ GitHub</a>
      <span class="dot">·</span>
      <span>v<span id="loginVersion">-</span></span>
      <span class="dot">·</span>
      <span>by Bob Vane</span>
    </div>
  </div>
</div>

<!-- Health History Modal (v2.32) -->
<div class="modal-overlay" id="healthHistoryModal">
  <div class="modal-content" style="max-width:640px">
    <div class="modal-header"><h3 id="healthHistoryTitle">📈 健康历史</h3><button class="modal-close" onclick="closeModal('healthHistoryModal')">✕</button></div>
    <div class="modal-body" id="healthHistoryBody"></div>
  </div>
</div>

<!-- Add Subscription Modal -->
<div class="modal-overlay" id="addSubModal">
  <div class="modal-content">
    <div class="modal-header"><h3>添加订阅</h3><button class="modal-close" onclick="closeModal('addSubModal')">✕</button></div>
    <div class="modal-body">
      <div class="form-group"><label>名称</label><input id="subName" placeholder="例如: My Airport"></div>
      <div class="form-group"><label>订阅 URL</label><input id="subUrl" placeholder="https://example.com/sub"></div>
      <button class="btn btn-primary" onclick="addSub()">➕ 添加</button>
    </div>
  </div>
</div>

<!-- Progress Modal (v2.17: 大刷新/拉取操作居中进度条，长时限 + 超时报错) -->
<div class="modal-overlay" id="progressModal">
  <div class="modal-content" style="max-width:480px;text-align:center">
    <div class="modal-header" style="justify-content:center"><h3 id="progressTitle">⏳ 处理中</h3></div>
    <div class="modal-body">
      <div style="margin:4px 0 16px;font-size:14px;color:var(--text2);min-height:20px" id="progressStatus">请稍候…</div>
      <div style="height:8px;background:rgba(0,0,0,0.08);border-radius:999px;overflow:hidden">
        <div id="progressBar" style="height:100%;width:0%;background:var(--accent);border-radius:999px;transition:width .3s ease"></div>
      </div>
      <div style="margin-top:12px;font-size:13px;color:var(--text2)">
        <span id="progressTimer">00:00</span> / <span id="progressCap">02:00</span>
      </div>
    </div>
  </div>
</div>

<!-- Config Preview Modal -->
<div class="modal-overlay" id="configModal">
  <div class="modal-content" style="max-width:800px">
    <div class="modal-header"><h3>📄 配置预览</h3><button class="modal-close" onclick="closeModal('configModal')">✕</button></div>
    <div class="modal-body">
      <div style="margin-bottom:12px">
        <label style="font-size:14px;color:var(--text2)">选择格式：</label>
        <select id="previewFormatSelect" onchange="previewSelect()" style="max-width:260px">
          <option value="mihomo">🐱 Mihomo / Clash / Stash</option>
          <option value="singbox">📦 Sing-box</option>
          <option value="v2ray">📄 V2ray (Base64)</option>
          <option value="v2rayn">📱 V2RayNG</option>
          <option value="nekoray">🪐 NekoRay</option>
          <option value="shadowrocket">🚀 Shadowrocket</option>
        </select>
        <button class="btn btn-primary btn-sm" onclick="previewSelect(true)" style="margin-left:8px">👉 加载</button>
        <button class="btn btn-sm" onclick="downloadConfigByFormat()" style="margin-left:8px">💾 下载配置文件</button>
      </div>
      <pre id="configPreview" style="background:var(--bg);border:1px solid var(--border);border-radius:6px;padding:12px;font-size:14px;overflow:auto;max-height:60vh;white-space:pre-wrap;word-break:break-all">选择格式查看预览</pre>
    </div>
  </div>
</div>

<!-- QR 码 Modal -->
<div class="modal-overlay" id="qrModal">
  <div class="modal-content" style="max-width:380px;text-align:center">
    <div class="modal-header"><h3>📱 扫码订阅</h3><button class="modal-close" onclick="closeModal('qrModal')">✕</button></div>
    <div class="modal-body">
      <div id="qrContainer" style="display:inline-block;background:#fff;padding:16px;border-radius:12px;margin:8px 0"></div>
      <p id="qrFormatName" style="margin:8px 0 4px;font-weight:600"></p>
      <p style="font-size:14px;color:var(--text2)">用代理客户端扫描此码导入订阅</p>
    </div>
  </div>
</div>

<script>
// ============ State ============
let state = { subscriptions: [], nodes: [], nodeHealth: {}, nodeLatencySort: null, nodeDropLatency: 2000, currentPage: 'dashboard', authenticated: false, dashboardPrefetch: null };

// ============ Theme ============
const themes = ['light', 'dark'];
let themeIdx = 0;
function applyTheme(t) {
  document.documentElement.dataset.theme = t;
  document.getElementById('themeBtn').textContent = t === 'dark' ? '☀️' : '🌙';
  try { localStorage.setItem('subnext-theme', t); } catch (e) {}
}
function cycleTheme() {
  themeIdx = (themeIdx + 1) % themes.length;
  applyTheme(themes[themeIdx]);
}
(function initTheme() {
  let saved = null;
  try { saved = localStorage.getItem('subnext-theme'); } catch (e) {}
  if (!saved && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) saved = 'dark';
  if (saved === 'dark') { themeIdx = 1; }
  applyTheme(saved || themes[themeIdx]);
})();

// ============ Toast ============
function toast(msg, type = 'success') {
  const el = document.createElement('div');
  el.className = \`toast toast-\${type}\`;
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => el.remove(), 3000);
}

// ============ Modal ============
function showModal(id) { document.getElementById(id).classList.add('show'); }
function closeModal(id) { document.getElementById(id).classList.remove('show'); }
document.addEventListener('click', function(e) {
  if (e.target.classList.contains('modal-overlay')) e.target.classList.remove('show');
});

// ============ Progress Modal (v2.17) ============
// 大刷新/拉取操作（订阅更新/重新检测国家码）居中弹进度条：显示进度 + 计时 + 硬性上限，超时报错。
let _progressTimer = null;
let _progressElapsed = 0;

function fmtClock(sec) {
  const m = String(Math.floor(sec / 60)).padStart(2, '0');
  const s = String(Math.floor(sec % 60)).padStart(2, '0');
  return \`\${m}:\${s}\`;
}

// 打开进度弹窗。capMs = 硬性上限（超时自动报错），非确定进度从 10% 起步向 95% 慢速爬升示意“仍在跑”
function showProgress(title, capMs = 120000) {
  closeProgress();
  document.getElementById('progressTitle').textContent = title;
  document.getElementById('progressStatus').textContent = '请稍候…';
  const bar = document.getElementById('progressBar');
  bar.style.width = '10%';
  document.getElementById('progressCap').textContent = fmtClock(capMs / 1000);
  document.getElementById('progressTimer').textContent = '00:00';
  document.getElementById('progressModal').classList.add('show');
  _progressElapsed = 0;
  // 伪进度：前 90% 缓慢爬升（真实成功时 closeProgress 跳到 100%），剩余 10% 留给超时兜底
  _progressTimer = setInterval(() => {
    _progressElapsed += 200;
    const el = document.getElementById('progressTimer');
    if (el) el.textContent = fmtClock(_progressElapsed / 1000);
    const ratio = Math.min(_progressElapsed / capMs, 0.95);
    bar.style.width = \`\${10 + ratio * 85}%\`;
  }, 200);
}

function updateProgress(text) {
  const el = document.getElementById('progressStatus');
  if (el && text) el.textContent = text;
}

function closeProgress(errMsg) {
  if (_progressTimer) { clearInterval(_progressTimer); _progressTimer = null; }
  const modal = document.getElementById('progressModal');
  if (!modal) return;
  const bar = document.getElementById('progressBar');
  const st = document.getElementById('progressStatus');
  if (errMsg) {
    bar.style.width = '100%';
    bar.style.background = 'var(--red)';
    if (st) st.textContent = '❌ ' + errMsg;
    setTimeout(() => modal.classList.remove('show'), 1600);
  } else {
    bar.style.width = '100%';
    setTimeout(() => modal.classList.remove('show'), 400);
  }
}

// 带进度弹窗的长操作封装（async）：capMs 超时报帅；请求本身的 timeout 负责真正中断
async function runWithProgress({ title, capMs = 120000, fn }) {
  showProgress(title, capMs);
  let done = false;
  const hardTimer = setTimeout(() => {
    if (!done) { closeProgress('操作超时，请稍后重试'); done = true; }
  }, capMs);
  try {
    const res = await fn();
    if (done) throw new Error('操作超时');
    clearTimeout(hardTimer); done = true;
    closeProgress();
    return res;
  } catch (e) {
    clearTimeout(hardTimer); done = true;
    closeProgress((e && e.name === 'AbortError') ? '请求超时，请重试' : ((e && e.message) || '操作失败'));
    throw e;
  }
}

// ============ API ============
// 带超时的 fetch 封装：避免网络挂起（黑洞）导致请求永不返回 → 白屏
// v2.16.0：支持 per-call timeout（options.timeout ms），abort 改为友好中文文案
function fetchWithTimeout(url, options = {}, ms = 15000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  return fetch(url, Object.assign({}, options, { signal: controller.signal }))
    .finally(() => clearTimeout(timer));
}

async function api(path, options = {}) {
  const urlParams = new URLSearchParams(window.location.search);
  const token = urlParams.get('token');
  const sep = path.includes('?') ? '&' : '?';
  const url = '/api' + path + (token ? \`\${sep}token=\${token}\` : '');
  // v2.16.0：从 options 读可选 timeout（默认 15s，订阅更新等重操作可传更长）
  const timeout = options.timeout !== undefined ? options.timeout : 15000;
  const opts = Object.assign({}, options);
  delete opts.timeout;
  let res;
  try {
    res = await fetchWithTimeout(url, { method: 'GET', headers: { 'Content-Type': 'application/json' }, credentials: 'include', ...opts }, timeout);
  } catch (e) {
    if (e && e.name === 'AbortError') throw new Error('请求超时，请重试');
    throw e;
  }
  const data = await res.json();
  if (!res.ok) throw new Error(data.error?.message || 'Request failed');
  return data;
}

// ============ Auth ============
async function checkSession() {
  try {
    // 首屏 bootstrap：登录态 + 用户名 + 当前页数据一次拿回
    // （原来是串行 3 次往返：/auth/session → /auth/username → /dashboard）
    const data = await api('/auth/session?page=' + encodeURIComponent(state.currentPage));
    if (data.data?.authenticated) {
      state.authenticated = true;
      document.getElementById('loginPage').style.display = 'none';
      document.getElementById('app').style.display = 'block';
      // 刷新页面恢复会话时，同步右上角用户名
      const badge = document.getElementById('userBadge');
      if (badge && data.data.username) badge.textContent = data.data.username;
      // 首屏数据随登录态一起返回，存起来交给 switchPage→loadDashboard 直接渲染
      if (data.data.dashboard) state.dashboardPrefetch = data.data.dashboard;
      return true;
    }
  } catch {}
  state.authenticated = false;
  document.getElementById('loginPage').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
  return false;
}

async function login() {
  const username = document.getElementById('loginUsername').value.trim() || 'admin';
  const password = document.getElementById('loginPassword').value;
  if (!password) { toast('请输入密码', 'error'); return; }
  try {
    await api('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) });
    document.getElementById('loginPassword').value = '';
    toast('登录成功');
    // 右上角用户徽标显示实际登录用户名
    const badge = document.getElementById('userBadge');
    if (badge) badge.textContent = username;
    state.authenticated = true;
    document.getElementById('loginPage').style.display = 'none';
    document.getElementById('app').style.display = 'block';
    // 退出后重登，始终默认进入仪表盘页（switchPage 内部会加载 dashboard 数据）
    switchPage('dashboard');
  } catch (e) {
    toast('密码错误: ' + e.message, 'error');
  }
}

async function logout() {
  try { await api('/auth/logout', { method: 'POST' }); } catch {}
  state.authenticated = false;
  document.getElementById('loginPage').style.display = 'flex';
  document.getElementById('app').style.display = 'none';
}

// ============ Page Switching ============
function switchPage(page) {
  state.currentPage = page;
  document.querySelectorAll('.nav-tab').forEach(t => t.classList.toggle('active', t.dataset.page === page));
  document.querySelectorAll('.page').forEach(p => p.classList.toggle('active', p.id === 'page-' + page));
  window.location.hash = page;
  // 未登录时不加载任何数据（避免 401 toast）
  if (!state.authenticated) return;
  if (page === 'dashboard') loadDashboard();
  if (page === 'subscribe') loadSubscriptions();
  if (page === 'nodes') loadNodes();
  if (page === 'output') loadOutput();
  if (page === 'rules') { loadRules(); ensureCatalogLoaded(); }
  if (page === 'settings') { loadSettings(); loadCurrentUsername(); }
}

// ============ 分流规则 ============
// 规则大类数据由后端 /api/rules/groups 提供（来源：src/data/metacubex-rules.ts）
let RULE_GROUPS = [];
// 整组取消的规则大类 key（v2.27.0 锁死模型：内置规则只能整组开关）
let disabledGroupKeys = new Set();
// 自定义规则选中集合（自定义规则随所属组位置输出，可逐条勾选）
let customSelected = new Set();
let ruleExpanded = {};

function initRuleState() {
  ruleExpanded = {};
  customSelected = new Set();
  RULE_GROUPS.forEach(g => { ruleExpanded[g.key] = false; });
}

function isGroupOn(key) { return !disabledGroupKeys.has(key); }

function renderRulesTree() {
  const container = document.getElementById('rulesTree');
  container.innerHTML = RULE_GROUPS.map((g, gi) => {
    const on = isGroupOn(g.key);
    const cls = ruleExpanded[g.key] ? 'open' : '';
    let itemsHTML;
    if (g.items.length === 0) {
      itemsHTML = \`<div class="rules-empty" style="padding:10px 14px;font-size:14px;color:var(--text2)">暂无预置规则，从右侧规则库添加</div>\`;
    } else {
      itemsHTML = g.items.map(it => {
        const isCustom = it.custom || (window._customRules && window._customRules.includes(it.id));
        if (isCustom) {
          // 自定义规则：可逐条勾选 + 删除
          const checked = on && customSelected.has(it.id);
          return \`<label class="rules-item rules-custom">
            <input type="checkbox" data-rule-check data-g="\${gi}" data-id="\${escHtml(it.id)}" \${checked ? 'checked' : ''} onchange="onRuleItemChange(this)">
            <span class="rule-label">
              <span class="rule-main">
                <span class="rule-name">\${escHtml(it.label)}</span>
                <span class="rule-id">\${escHtml(it.tag)}:\${escHtml(it.id)}</span>
              </span>
              <span title="删除此规则" style="cursor:pointer;color:var(--red);font-size:16px;margin-left:8px;opacity:.8;flex:none" class="rule-del" onclick="event.stopPropagation();deleteCustomRule('\${escHtml(it.id)}')">🗑</span>
            </span>
          </label>\`;
        }
        // 内置规则：锁死，只能整组开关（2026-09-19 用户拍板）
        return \`<div class="rules-item rules-locked \${on ? '' : 'rules-off'}">
          <span class="rules-lock-icon" title="内置规则锁死，只能整组开关">🔒</span>
          <span class="rule-label">
            <span class="rule-main">
              <span class="rule-name">\${escHtml(it.label)}</span>
              <span class="rule-id">\${escHtml(it.tag)}:\${escHtml(it.id)}</span>
            </span>
          </span>
        </div>\`;
      }).join('');
    }
    return \`
      <div class="rules-group \${on ? '' : 'rules-group-off'}">
        <div class="rules-group-head \${cls}" data-g="\${gi}" onclick="toggleRuleGroup(\${gi})">
          <span class="rules-arrow">▶</span>
          <input type="checkbox" data-group-check data-g="\${gi}" \${on ? 'checked' : ''} onclick="event.stopPropagation()" onchange="onRuleGroupChange(this)">
          <span class="rules-group-title"><span class="rules-group-index">\${gi + 1}</span>\${g.icon || ''} \${g.name}</span>
          <span class="rules-group-count">\${on ? '开启' : '已关闭'}</span>
        </div>
        <div class="rules-items\${on ? '' : ' rules-off'}">\${itemsHTML}</div>
      </div>\`;
  }).join('');
  updateRulesCount();
  renderPresetBar();
}

function toggleRuleGroup(gi) {
  ruleExpanded[RULE_GROUPS[gi].key] = !ruleExpanded[RULE_GROUPS[gi].key];
  renderRulesTree();
}

function onRuleGroupChange(cb) {
  const gi = +cb.dataset.g;
  const key = RULE_GROUPS[gi].key;
  if (cb.checked) disabledGroupKeys.delete(key);
  else disabledGroupKeys.add(key);
  renderRulesTree();
  saveDisabledGroups();
}

function onRuleItemChange(cb) {
  const id = cb.dataset.id;
  if (cb.checked) customSelected.add(id);
  else customSelected.delete(id);
  renderRulesTree();
  saveRuleSelection();
}

function updateRulesCount() {
  const onGroups = RULE_GROUPS.filter(g => isGroupOn(g.key)).length;
  document.getElementById('rulesCount').textContent = onGroups;
}

// 把整组取消的 key 保存到后端
function saveDisabledGroups() {
  fetch('/api/rules/groups/disabled', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ keys: [...disabledGroupKeys] }),
  }).then(r => r.json()).then(() => {}).catch(() => toast('规则组保存失败', 'error'));
}

// 把自定义规则的选中 id 保存到后端
function saveRuleSelection() {
  fetch('/api/rules/selection', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ids: [...customSelected] }),
  }).then(r => r.json()).then(() => {}).catch(() => toast('规则保存失败', 'error'));
}

function selectAllRules(check) {
  RULE_GROUPS.forEach(g => {
    if (check) disabledGroupKeys.delete(g.key);
    else disabledGroupKeys.add(g.key);
  });
  renderRulesTree();
  saveDisabledGroups();
}

// ============ 快速预设 ============
// 以"组"为单位：整组开关；组内内置规则锁死，自定义规则随其组开关
const RULE_PRESETS = [
  { key: 'mini', label: '🟢 极简', groups: ['ads','china-direct','ai','youtube','github','media'] },
  { key: 'mini-crypto', label: '🟢 极简+加密', groups: ['ads','china-direct','ai','youtube','github','media','crypto'] },
  { key: 'standard', label: '🔵 标准', groups: ['ads','china-direct','ai','youtube','google','github','microsoft','apple','media','game'] },
  { key: 'standard-crypto', label: '🔵 标准+加密', groups: ['ads','china-direct','ai','youtube','google','github','microsoft','apple','media','game','crypto'] },
  { key: 'full', label: '🟣 完全体', groups: null },  // null = 除 crypto 外全部
  { key: 'full-crypto', label: '🟣 完全+加密', groups: 'ALL' },
];

function presetGroups(p) {
  if (p.groups === 'ALL') return RULE_GROUPS.map(g => g.key);
  if (p.groups === null) return RULE_GROUPS.filter(g => g.key !== 'crypto').map(g => g.key);
  return p.groups;
}

function applyPreset(key) {
  const p = RULE_PRESETS.find(x => x.key === key);
  if (!p) return;
  const on = new Set(presetGroups(p));
  disabledGroupKeys = new Set(RULE_GROUPS.map(g => g.key).filter(k => !on.has(k)));
  renderRulesTree();
  saveDisabledGroups();
  toast(\`已应用预设「\${p.label.replace(/^\\S+\\s/, '')}」\`);
}

// 当前开关状态与某预设完全一致时高亮；手动改动后自然失配
function activePresetKey() {
  for (const p of RULE_PRESETS) {
    const on = new Set(presetGroups(p));
    const curOn = RULE_GROUPS.map(g => g.key).filter(k => isGroupOn(k));
    const same = RULE_GROUPS.length === 0 || (curOn.length === on.size && curOn.every(k => on.has(k)));
    if (same) return p.key;
  }
  return null;
}

function renderPresetBar() {
  const bar = document.getElementById('presetBar');
  if (!bar || RULE_GROUPS.length === 0) return;
  const act = activePresetKey();
  bar.innerHTML = RULE_PRESETS.map(p =>
    \`<button class="btn btn-sm \${p.key === act ? 'btn-primary' : ''}" onclick="applyPreset('\${p.key}')">\${p.label}</button>\`
  ).join('');
}

function resetRulesExpanded() {
  RULE_GROUPS.forEach(g => { ruleExpanded[g.key] = true; });
  renderRulesTree();
}

function loadRules() {
  // 首次加载时从后端拉取规则大类 + 已保存的选择 + 自定义规则 + 整组开关，同时显示加载状态
  const container = document.getElementById('rulesTree');
  if (RULE_GROUPS.length === 0) {
    container.innerHTML = '<div class="rules-loading">⏳ 正在加载规则…</div>';
    Promise.all([
      fetch('/api/rules/groups').then(r => r.json()),
      fetch('/api/rules/selection').then(r => r.json()),
      fetch('/api/rules/custom').then(r => r.json()),
      fetch('/api/rules/groups/disabled').then(r => r.json()),
    ])
      .then(([groupsRes, selRes, customRes, disabledRes]) => {
        if (groupsRes.success && groupsRes.data && groupsRes.data.groups) {
          RULE_GROUPS = groupsRes.data.groups;
          window._customRules = (customRes.data?.rules || []).map(r => r.id);
          initRuleState();
          // 应用整组取消的 key
          if (disabledRes.success && disabledRes.data && Array.isArray(disabledRes.data.keys)) {
            disabledGroupKeys = new Set(disabledRes.data.keys);
          }
          // 应用自定义规则的选中集合（内置规则已锁死，无需从 selection 恢复）
          if (selRes.success && selRes.data && Array.isArray(selRes.data.ids)) {
            selRes.data.ids.forEach(id => {
              if (window._customRules.includes(id)) customSelected.add(id);
            });
          }
          renderRulesTree();
        } else {
          container.innerHTML = '<div class="rules-loading" style="color:var(--red)">❌ 规则数据加载失败</div>';
        }
      })
      .catch(() => {
        container.innerHTML = '<div class="rules-loading" style="color:var(--red)">❌ 规则数据加载失败</div>';
      });
  } else {
    renderRulesTree();
  }
}

// ============ Dashboard ============
function renderDashboard(d) {
  document.getElementById('statSubs').textContent = d.subscriptions;
  document.getElementById('statEnabledSubs').textContent = d.enabledSubscriptions ?? '-';
  document.getElementById('statDisabledSubs').textContent = d.disabledSubscriptions ?? '-';
  // v2.36.3：节点口径与「节点列表」页一致 —— 去重后实际数 + 测活健康
  document.getElementById('statNodes').textContent = d.uniqueNodes ?? d.nodes;
  const sub = document.getElementById('statNodesSub');
  if (sub) sub.textContent = (d.duplicates ? \`含重复 \${d.nodes}（去重 -\${d.duplicates}）\` : '无重复');
  document.getElementById('statAlive').textContent = d.alive ?? 0;
  document.getElementById('statDead').textContent = d.dead ?? 0;
  document.getElementById('statDropped').textContent = d.droppedNodes ?? 0;
  document.getElementById('statLastProbe').textContent = d.lastProbe ? new Date(d.lastProbe).toLocaleString('zh-CN', { hour12: false }) : '未测活';
  // 协议分布
  const proto = d.protoCount || {};
  const protoNames = { vmess:'VMess', vless:'VLESS', trojan:'Trojan', shadowsocks:'SS', ss:'SS' };
  const protoStr = Object.entries(proto)
    .map(([k,v]) => (protoNames[k] || k) + ': ' + v)
    .join(' · ');
  document.getElementById('statProto').textContent = protoStr || '-';
  // 最近更新时间
  document.getElementById('statUpdate').textContent = d.lastUpdate ? new Date(d.lastUpdate).toLocaleString() : '暂无';
}

async function loadDashboard() {
  try {
    // 首屏数据可能已随 bootstrap 一起返回，命中后不再重复请求
    const prefetched = state.dashboardPrefetch;
    state.dashboardPrefetch = null;
    renderDashboard(prefetched || (await api('/dashboard')).data);
  } catch { toast('加载仪表盘失败', 'error'); }
  loadOperationLogs();
}

// v2.32: 仪表盘「最近动态」卡片（操作日志，最近 10 条）
async function loadOperationLogs() {
  const list = document.getElementById('opLogList');
  if (!list) return;
  try {
    const res = await api('/operation-log?limit=10');
    const logs = res.data || [];
    if (logs.length === 0) {
      list.innerHTML = '<div style="padding:8px;color:var(--text2)">暂无操作记录</div>';
      return;
    }
    list.innerHTML = logs.map(l => {
      const t = new Date(l.timestamp);
      const timeStr = t.toLocaleString('zh-CN', { hour12: false });
      const icon = l.type === 'subscription_update' ? '🔄'
        : l.type === 'geoip_update' ? '🌐'
        : l.type === 'node_disabled' ? '🚫'
        : l.type === 'node_recovered' ? '✅'
        : l.type === 'probe' ? '⚡'
        : l.type === 'manual_action' ? '⚙️'
        : l.type === 'cache_invalidated' ? '💾'
        : '📝';
      return \`<div style="padding:6px 8px;border-bottom:1px solid var(--border);line-height:1.5">
        <span style="color:var(--text2);font-size:12px">\${timeStr}</span>
        <span>\${icon}</span>
        <span style="margin-left:4px">\${escHtml(l.message)}</span>
      </div>\`;
    }).join('');
  } catch { list.innerHTML = '<div style="padding:8px;color:var(--red)">加载失败</div>'; }
}

async function clearOperationLogs() {
  if (!confirm('确定清空全部操作日志？此操作不可恢复。')) return;
  try {
    await api('/operation-log', { method: 'DELETE' });
    toast('操作日志已清空');
    loadOperationLogs();
  } catch (e) { toast('清空失败: ' + e.message, 'error'); }
}

// ============ Dashboard CF 请求统计（v2.18.0） ============

// ============ Subscriptions ============
async function loadSubscriptions() {
  try {
    const data = await api('/subscriptions');
    state.subscriptions = data.data || [];
    renderSubTable();
  } catch { toast('加载订阅失败', 'error'); }
}

function renderSubTable() {
  const tbody = document.getElementById('subTableBody');
  if (state.subscriptions.length === 0) {
    tbody.innerHTML = '<tr><td colspan="6" class="text-center" style="color:var(--text2);padding:24px">暂无订阅，点击右上角添加</td></tr>';
    return;
  }
  tbody.innerHTML = state.subscriptions.map(s => \`
    <tr>
      <td><strong>\${escHtml(s.name)}</strong></td>
      <td style="font-size:14px;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="\${escHtml(s.url || '')}">
        \${s.url ? \`<a href="\${escHtml(s.url)}" target="_blank" rel="noopener" style="color:var(--accent);text-decoration:none">\${escHtml(s.url)}</a>\` : '-'}
      </td>
      <td>
        \${s.enabled
          ? '<span class="status-active">✅ 已启用</span>'
          : '<span class="status-disabled">⏸ 未启用</span>'}
        \${s.status === 'error' && s.enabled ? ' <span class="status-error">❌ 更新失败</span>' : ''}
      </td>
      <td>\${s.nodeCount ?? 0}</td>
      <td style="font-size:14px;color:var(--text2)">\${s.updatedAt ? new Date(s.updatedAt).toLocaleString() : '-'}</td>
      <td>
        <button class="btn btn-sm" onclick="toggleSub('\${s.id}')">\${s.enabled ? '⏸ 停用' : '▶ 启用'}</button>
        <button class="btn btn-sm" onclick="updateSub('\${s.id}')">🔄 更新</button>
        <button class="btn btn-sm btn-danger" onclick="deleteSub('\${s.id}')">🗑 删除</button>
      </td>
    </tr>
  \`).join('');
}

function showAddSub() { showModal('addSubModal'); }

async function addSub() {
  const name = document.getElementById('subName').value.trim();
  const url = document.getElementById('subUrl').value.trim();
  if (!name || !url) { toast('请填写名称和 URL', 'error'); return; }
  try {
    const data = await api('/subscriptions', { method: 'POST', body: JSON.stringify({ name, url }) });
    toast('添加成功');
    document.getElementById('subName').value = '';
    document.getElementById('subUrl').value = '';
    closeModal('addSubModal');
    // 乐观更新：立即把新订阅插进列表（避免 KV 最终一致性的读取延迟）
    state.subscriptions.unshift({
      id: data.data.id,
      name: name,
      enabled: true,
      status: 'active',
      nodeCount: 0,
      updatedAt: Date.now(),
    });
    renderSubTable();
    // 后台再拉一次，确保拿到服务器最新数据（含其他字段）
    setTimeout(loadSubscriptions, 800);
  } catch (e) { toast('添加失败: ' + e.message, 'error'); }
}

async function updateSub(id) {
  const btn = document.querySelector(\`button[onclick*="updateSub('\${id}')"]\`);
  if (btn) { if (btn.disabled) return; btn.disabled = true; btn.textContent = '⏳ 更新中'; }
  try {
    // v2.17.0：居中进度条，120s 长时限（后台 prewarm 已异步，只等订阅抓取+解析）
    const res = await runWithProgress({
      title: '🔄 更新订阅',
      capMs: 120000,
      fn: () => api('/subscriptions/' + id + '/update', { method: 'POST', timeout: 120000 }),
    });
    toast('更新成功');
    if (res && res.data) updateProgress(\`✅ 更新完成：\${res.data.nodeCount ?? 0} 个节点\`);
    loadSubscriptions();
  } catch (e) { toast('更新失败: ' + e.message, 'error'); }
  finally {
    if (btn) { btn.disabled = false; btn.textContent = '🔄 更新'; }
  }
}

async function deleteSub(id) {
  if (!confirm('确定删除此订阅？')) return;
  try {
    await api('/subscriptions/' + id, { method: 'DELETE' });
    toast('删除成功');
    loadSubscriptions();
  } catch (e) { toast('删除失败: ' + e.message, 'error'); }
}

// 启用/停用订阅（不删除，留着以后再用）2026-09-24
async function toggleSub(id) {
  const sub = state.subscriptions.find(x => x.id === id);
  if (!sub) return;
  const enabled = !sub.enabled;
  try {
    await api('/subscriptions/' + id + '/enabled', { method: 'POST', body: JSON.stringify({ enabled }) });
    sub.enabled = enabled;
    renderSubTable();
    toast(enabled ? '已启用' : '已停用');
  } catch (e) { toast('操作失败: ' + e.message, 'error'); }
}

// ============ Nodes ============
// v2.16.0：loadNodes 在途合并——同一时刻只允许一个 /nodes 请求在飞，后续调用复用同一 Promise，
//           避免切页/刷新连点时并发打爆 KV（配合后端 filterUnlocatedServers 分批并发，节点列表秒开）
let _loadNodesPromise = null;
async function loadNodes(forceRefresh = false) {
  if (!forceRefresh && _loadNodesPromise) return _loadNodesPromise;
  const p = (async () => {
    try {
      const res = await api('/nodes');
      state.nodes = res.data || [];
      // 显示去重统计
      if (res.stats) {
        const setStat = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = String(v ?? 0); };
        setStat('statsOriginal', res.stats.original);
        setStat('statsDuplicates', res.stats.duplicates);
        setStat('statsUnique', res.stats.unique);
        setStat('statsGeoUnlocated', res.stats.geoUnlocated);
        if (res.stats.dropLatencyMs) state.nodeDropLatency = res.stats.dropLatencyMs;
      }
      // v2.32：并行拉健康快照（延迟/状态列数据源）。失败不阻断节点列表。
      try {
        const hr = await api('/nodes/health');
        const map = {};
        let last = 0;
        for (const h of (hr.data || [])) {
          map[h.fingerprint] = h;
          if (h.timestamp > last) last = h.timestamp;
        }
        state.nodeHealth = map;
        const el = document.getElementById('statsLastProbe');
        if (el) el.textContent = last ? new Date(last).toLocaleString('zh-CN', { hour12: false }) : '未测活';
      } catch { state.nodeHealth = {}; }
      renderNodes();
    } catch { toast('加载节点失败', 'error'); }
    loadGeoPending();
  })().finally(() => { _loadNodesPromise = null; });
  _loadNodesPromise = p;
  return p;
}

// 读取未识别国家码自动重试状态（v2.19.1）——连续重试 10 次后仍剩的 IP 显示提示横幅「建议检查节点正确性」
async function loadGeoPending() {
  const banner = document.getElementById('geoPendingBanner');
  if (!banner) return;
  try {
    const res = await api('/nodes/geo-pending');
    const d = (res && res.data) || {};
    const unlocated = (d.unlocatedServers || []).filter(Boolean);
    const retryCount = d.retryCount || 0;
    if (unlocated.length > 0 && retryCount >= 10) {
      banner.style.display = '';
      banner.textContent = \`⚠️ 已自动重试 \${retryCount} 次国家码识别，仍有 \${unlocated.length} 个节点未识别国家码：\${unlocated.join('、')}。建议检查这些节点的 IP/域名是否正确。\`;
    } else {
      banner.style.display = 'none';
    }
  } catch { banner.style.display = 'none'; }
}

// 手动触发重新检测未识别国家码（POST /api/nodes/geo-redetect，复用后端批次+限流管线）
async function redetectGeo() {
  const btn = event.target;
  const orig = btn ? btn.textContent : null;
  if (btn) btn.disabled = true;
  try {
    // v2.17.0：居中进度条，120s 长时限；geo-redetect 并发锁 60s 幂等，真实耗时取决于未识别数量
    const res = await runWithProgress({
      title: '🔍 重新检测国家码',
      capMs: 120000,
      fn: () => api('/nodes/geo-redetect', { method: 'POST', body: JSON.stringify({ scope: 'unlocated' }), timeout: 120000 }),
    });
    const d = (res && res.data) || {};
    let msg = \`✅ 重新检测完成：检索 \${d.queried ?? 0}，新识别 \${d.resolved ?? 0}，失败 \${d.failed ?? 0}；剩余未识别 \${d.unlocatedAfter ?? 0}\`;
    if (Array.isArray(d.unlocatedServers) && d.unlocatedServers.length) {
      const shown = d.unlocatedServers.slice(0, 8).join(', ');
      const more = d.unlocatedServers.length > 8 ? \` 等\${d.unlocatedServers.length}个\` : '';
      msg += \`：\${shown}\${more}\`;
    }
    updateProgress(msg);
    toast(msg);
    loadNodes(); // 刷新 stats（geoUnlocated 归零或减少）
  } catch (e) {
    const msg = (e && e.message) || '重新检测失败';
    // 409 GEO_SCAN_IN_PROGRESS / 429 已在 message 里带中文提示，直接透出
    toast('⚠️ ' + msg, 'error');
  } finally {
    if (btn) btn.disabled = false;
  }
}

// ============ 协议显示名（独立链路，只影响展示） ============
// VLESS 子类型判定源 = 节点链接原始表达式（type/security/pbk/flow），
// 因节点列表 API 未返回 transport/pbk/flow 字段，前端优先从整链保真 n.link 解析，
// 拿不到 link 参数再回退到节点字段。XTLS Vision 直接表达为 XTLS（XTLS 隐含 TCP）。
function parseVlessLink(n) {
  const out = { type: '', pbk: '', flow: '', security: '' };
  const link = n.link || '';
  const q = link.indexOf('?');
  if (q < 0) return out;
  const query = link.slice(q + 1).split('#')[0];
  query.split('&').forEach((pair) => {
    const eq = pair.indexOf('=');
    if (eq < 0) return;
    const k = pair.slice(0, eq);
    let v = pair.slice(eq + 1);
    try { v = decodeURIComponent(v); } catch { /* 保留原值 */ }
    if (k in out) out[k] = v;
  });
  return out;
}
function displayProtocol(n) {
  // 兼容直接传 protocol 字符串（历史调用点）：字符串没有 .protocol，取自身
  const p = typeof n === 'string' ? n : n.protocol;
  if (p === 'vmess') return 'VMess';
  if (p === 'trojan') return 'Trojan';
  if (p === 'ss') return 'Shadowsocks';
  if (p === 'ssr') return 'ShadowsocksR';
  if (p === 'hysteria2') return 'Hysteria2';
  if (p === 'tuic') return 'TUIC';
  if (p === 'wireguard') return 'WireGuard';
  if (p === 'anytls') return 'AnyTLS';
  if (p === 'vless') {
    const link = parseVlessLink(n);
    const t = link.type || (n.transport && n.transport.type) || 'tcp';
    const pbk = link.pbk || n.pbk;
    const flow = link.flow || n.flow;
    const security = link.security;
    const segs = [];
    // Reality（security=reality 或 pbk 存在即 Reality，可配 TCP/XHTTP/gRPC）
    if (security === 'reality' || pbk) segs.push('Reality');
    // XTLS 仅 TCP 系有效；XHTTP/WS/gRPC 与 Vision 互斥，无效组合忽略 flow
    if (flow && t === 'tcp') segs.push('XTLS');
    if (t === 'xhttp') segs.push('XHTTP');
    else if (t === 'ws') segs.push('WebSocket');
    else if (t === 'grpc') segs.push('gRPC');
    if (segs.length === 0) return 'VLESS TCP';
    return 'VLESS + ' + segs.join(' + ');
  }
  return p;
}
// VLESS 全子类型共享 tag-vless 一色，其余协议各一色
function protocolTagClass(protocol) {
  const known = ['vless', 'vmess', 'trojan', 'ss', 'ssr', 'hysteria2', 'tuic', 'wireguard', 'anytls'];
  return 'tag-' + (known.indexOf(protocol) >= 0 ? protocol : 'other');
}

// 节点最新延迟（v2.36：TLS RTT 优先，无则 TCP RTT；接口已带 latency 字段）
function nodeLatency(n) {
  if (n.latency != null) return n.latency;
  const h = state.nodeHealth[n.fingerprint];
  return h ? (h.tlsLatency ?? h.tcpLatency) : null;
}

// 默认排序：同国家聚在一起，国家内健康得分高的在前（无分/无国家靠后）
function defaultNodeOrder(a, b) {
  // v2.36.6：已抛弃节点恒排末尾（通着但太慢/不通的沉底，便于扫视）
  if (!!a.dropped !== !!b.dropped) return a.dropped ? 1 : -1;
  const ca = a.country || 'ZZ';
  const cb = b.country || 'ZZ';
  if (ca !== cb) return ca < cb ? -1 : 1;
  const sa = a.score ?? -1;
  const sb = b.score ?? -1;
  if (sa !== sb) return sb - sa;
  return (nodeLatency(a) ?? 1e9) - (nodeLatency(b) ?? 1e9);
}

// 点击「延迟」表头切换 升序 → 降序 → 取消
function sortNodesByLatency() {
  state.nodeLatencySort = state.nodeLatencySort === null ? 'asc' : (state.nodeLatencySort === 'asc' ? 'desc' : null);
  renderNodes();
}

function renderNodes() {
  const tbody = document.getElementById('nodesTableBody');
  const empty = document.getElementById('nodesEmpty');
  const search = document.getElementById('nodeSearch').value.toLowerCase();
  // v2.36：被熔断抛弃的节点也列出并标 🚫 —— 用户要能看到"哪些被抛弃了"（仅不输出到配置，记录保留、继续测活）
  let filtered = state.nodes.slice();
  if (search) filtered = filtered.filter(n => (n.name + ' ' + n.server).toLowerCase().includes(search));
  if (state.nodeLatencySort) {
    const dir = state.nodeLatencySort === 'asc' ? 1 : -1;
    filtered = filtered.sort((a, b) => {
      const la = nodeLatency(a), lb = nodeLatency(b);
      if (la == null && lb == null) return 0;
      if (la == null) return 1;  // 未测到延迟的节点恒排末尾
      if (lb == null) return -1;
      return (la - lb) * dir;
    });
  } else {
    filtered = filtered.sort(defaultNodeOrder);
  }
  // 顶部健康统计（v2.36.6：与仪表盘同口径 —— 有测活记录且非 alive 都算不通）
  const cnt = (f) => state.nodes.filter(f).length;
  const setStat2 = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = String(v); };
  setStat2('statsAlive', cnt(n => n.healthStatus === 'alive'));
  setStat2('statsDead', cnt(n => n.healthStatus && n.healthStatus !== 'alive'));
  setStat2('statsDropped', cnt(n => n.dropped));
  const mark = document.getElementById('latencySortMark');
  if (mark) mark.textContent = state.nodeLatencySort === 'asc' ? '▲' : (state.nodeLatencySort === 'desc' ? '▼' : '');
  if (filtered.length === 0) {
    tbody.innerHTML = '';
    empty.style.display = 'block';
    return;
  }
  empty.style.display = 'none';
  tbody.innerHTML = filtered.map(n => {
    const tagClass = protocolTagClass(n.protocol);
    const h = state.nodeHealth[n.fingerprint];
    const latency = nodeLatency(n);
    const latencyStr = latency != null ? latency + 'ms' : '—';
    const icon = !n.healthStatus ? '—' : ({ alive: '✅', dead: '❌', timeout: '⏱️', error: '⚠️' }[n.healthStatus] || '❓');
    const scoreStr = n.score != null ? \` 得分 \${n.score}\` : '';
    const tip = n.healthStatus ? \`得分 \${n.score}\${n.error ? ' · ' + n.error : ''} · 点击看趋势\` : '尚未测活 · 点击看趋势';
    const dropped = n.dropped ? '<span title="测活不通或延迟超过阈值，已从生成的配置中抛弃（记录保留，恢复后自动回来）" style="color:var(--danger)">🚫 已抛弃</span>' : '';
    const suspect = n.statusMachine === 'suspect' ? '<span title="连续失败，观察中" style="color:var(--orange)">⚠️</span> ' : '';
    const rowStyle = n.dropped ? ' style="opacity:0.55"' : '';
    return \`<tr\${rowStyle}>
      <td><button class="btn btn-sm node-lock-btn\${n.locked ? ' node-lock-on' : ''}" title="\${n.locked ? '已锁定：无视测活/延迟，强制进配置（点击解锁）' : '未锁定：跟随测活/延迟决定进出配置（点击锁定）'}" onclick="toggleNodeLock('\${escHtml(n.fingerprint)}', \${!n.locked})">\${n.locked ? '🔒' : '🔓'}</button></td>
      <td>\${escHtml(n.name)}</td>
      <td><span class="tag \${tagClass}">\${displayProtocol(n)}</span></td>
      <td style="font-size:14px">\${escHtml(n.server)}</td>
      <td>\${n.port}</td>
      <td>\${n.tls ? '✅' : '❌'}</td>
      <td style="font-size:14px;\${latency != null && latency > state.nodeDropLatency ? 'color:var(--red)' : ''}">\${latencyStr}</td>
      <td style="font-size:14px;cursor:pointer" title="\${escHtml(tip)}" onclick="showNodeHistory('\${escHtml(n.fingerprint)}')">\${suspect}\${icon}\${scoreStr} \${dropped}</td>
      <td><button class="btn btn-sm" onclick="copyNodeLink('\${escHtml(n.fingerprint)}')">📋 复制</button></td>
    </tr>\`;
  }).join('');
}

// ⚡ 立即测活：全量 TCP/TLS 探测（同步等待，走通用进度弹窗）
async function probeAllNodes() {
  try {
    const res = await runWithProgress({
      title: '⚡ 正在测活所有节点…',
      capMs: 180000,
      fn: () => api('/nodes/probe', { method: 'POST', timeout: 180000 }),
    });
    const s = res.stats || {};
    const parts = [\`共 \${s.total ?? res.nodeCount ?? 0}\`, \`存活 \${s.alive ?? 0}\`, \`不通 \${s.dead ?? 0}\`];
    if (s.avgLatency != null) parts.push(\`平均 \${s.avgLatency}ms\`);
    if (s.disabled) parts.push(\`已抛弃 \${s.disabled}\`);
    toast(\`测活完成 · \${parts.join(' · ')}\`);
    await loadNodes(true);
  } catch (e) { /* runWithProgress 已弹出失败提示 */ }
}

// ============ 节点健康历史（点击状态列弹出，纯前端折线图） ============
async function showNodeHistory(fingerprint) {
  const node = state.nodes.find(n => n.fingerprint === fingerprint);
  document.getElementById('healthHistoryTitle').textContent = \`📈 \${node ? node.name : fingerprint} · 健康历史\`;
  const body = document.getElementById('healthHistoryBody');
  body.innerHTML = '<p style="color:var(--text2)">加载中…</p>';
  showModal('healthHistoryModal');
  try {
    const res = await api(\`/nodes/health?fingerprint=\${encodeURIComponent(fingerprint)}\`, { timeout: 20000 });
    body.innerHTML = renderHealthChart(res.data || []);
  } catch (e) {
    body.innerHTML = \`<p style="color:var(--red)">加载失败：\${escHtml(e.message || '未知错误')}</p>\`;
  }
}

function renderHealthChart(hist) {
  const pts = hist.slice().sort((a, b) => a.timestamp - b.timestamp);
  if (pts.length === 0) return '<p style="color:var(--text2)">暂无历史数据（该节点尚未测活）</p>';
  const W = 560, H = 170, P = 30;
  const vals = pts.map(p => p.httpLatency ?? p.tcpLatency).filter(v => v != null);
  const maxV = Math.max(100, ...vals);
  const x = i => P + (pts.length === 1 ? (W - 2 * P) / 2 : i * (W - 2 * P) / (pts.length - 1));
  const y = v => H - P - (v / maxV) * (H - 2 * P);
  const dots = [], line = [];
  pts.forEach((p, i) => {
    const v = p.httpLatency ?? p.tcpLatency;
    if (v == null) return;
    line.push(\`\${line.length === 0 ? 'M' : 'L'}\${x(i).toFixed(1)},\${y(v).toFixed(1)}\`);
    dots.push(\`<circle cx="\${x(i).toFixed(1)}" cy="\${y(v).toFixed(1)}" r="3" fill="\${p.status === 'alive' ? 'var(--green)' : 'var(--red)'}"><title>\${new Date(p.timestamp).toLocaleString()} · \${v}ms · 得分 \${p.score}</title></circle>\`);
  });
  const fmtT = ts => new Date(ts).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  return \`
    <svg viewBox="0 0 \${W} \${H}" style="width:100%;height:auto">
      <line x1="\${P}" y1="\${H - P}" x2="\${W - P}" y2="\${H - P}" stroke="var(--border)"/>
      <line x1="\${P}" y1="\${P}" x2="\${P}" y2="\${H - P}" stroke="var(--border)"/>
      <text x="\${P - 4}" y="\${P + 4}" text-anchor="end" font-size="11" fill="var(--text2)">\${maxV}ms</text>
      <text x="\${P - 4}" y="\${H - P}" text-anchor="end" font-size="11" fill="var(--text2)">0</text>
      \${line.length ? \`<path d="\${line.join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2"/>\` : ''}
      \${dots.join('')}
      <text x="\${P}" y="\${H - 8}" font-size="11" fill="var(--text2)">\${fmtT(pts[0].timestamp)}</text>
      <text x="\${W - P}" y="\${H - 8}" text-anchor="end" font-size="11" fill="var(--text2)">\${fmtT(pts[pts.length - 1].timestamp)}</text>
    </svg>
    <p style="color:var(--text2);font-size:13px;margin-top:8px">共 \${pts.length} 次探测 · ✅ 成功 ❌ 失败 · 悬停查看单次详情</p>\`;
}

function filterNodes() { renderNodes(); }

// ============ 节点名清洗（v2.35 已废弃：改为生成时自动命名，见 config.service.smartRename） ============

// 复制文本到剪贴板（v2.30.5）
// ⚠️ 非安全上下文（内网 http 直连，如 http://NAS-IP:20130）浏览器**不提供** navigator.clipboard，
// 直接写 navigator.clipboard.writeText(...) 会同步抛 TypeError —— .catch() 还没挂上就炸了，
// 表现为"点了复制没反应、也没提示"。所有复制入口统一走这里：
// 能用 Clipboard API 就用，不能用回退 execCommand('copy')（同样能在 http 下工作）。
async function copyText(text, okMsg) {
  try {
    await navigator.clipboard.writeText(text);
    toast(okMsg);
    return true;
  } catch {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.position = 'fixed';
    ta.style.top = '-1000px';
    document.body.appendChild(ta);
    ta.select();
    ta.setSelectionRange(0, text.length); // iOS Safari 需要
    let ok = false;
    try { ok = document.execCommand('copy'); } catch { ok = false; }
    ta.remove();
    toast(ok ? okMsg : '复制失败，请手动选中复制', ok ? undefined : 'error');
    return ok;
  }
}

function copyNodeLink(fingerprint) {
  const node = state.nodes.find(n => n.fingerprint === fingerprint);
  if (!node || !node.link) { toast('节点链接不可用', 'error'); return; }
  copyText(node.link, '已复制单节点链接');
}

// v2.36.9：节点锁定（替换原勾选框）—— 锁定 = 无视测活/延迟，强制进配置
async function toggleNodeLock(fp, locked) {
  const node = state.nodes.find(n => n.fingerprint === fp);
  if (!node) return;
  node.locked = locked;
  renderNodes();
  refreshNodeCount();
  try {
    await api('/nodes/locked', { method: 'POST', body: JSON.stringify({ fingerprint: fp, locked }) });
    toast(locked ? '🔒 已锁定：该节点将强制进配置' : '🔓 已解锁：跟随测活/延迟判定');
  } catch (e) {
    node.locked = !locked;
    renderNodes();
    toast('保存失败: ' + e.message, 'error');
  }
}

// ============ Output ============
function loadOutput() {
  refreshNodeCount();
  renderOutputUrls();
}

async function refreshNodeCount() {
  try {
    const data = await api('/nodes');
    state.nodes = data.data || [];
    const total = state.nodes.length;
    // 进配置 = 未被抛弃（锁定节点即使被抛弃也进配置），与 getNodes 同口径
    const inConfig = state.nodes.filter(n => !(n.dropped && !n.locked)).length;
    document.getElementById('outputNodeCount').textContent = \`\${inConfig} 个节点进配置（共 \${total}）\`;
    // 同步节点页锁定状态（如果已加载）
    if (state.currentPage === 'nodes') renderNodes();
  } catch { toast('刷新节点数失败', 'error'); }
}

function renderOutputUrls() {
  const baseUrl = window.location.origin + '/sub';
  // 分组：带分流规则输出 / 纯节点输出（无分流规则）
  const groups = [
    { label: '分流配置（含策略组 + 规则）',
      formats: [
        { key: 'mihomo',    name: '🐱 Mihomo',       desc: 'Mihomo / Clash Meta / OpenClash / Stash' },
      ]},
    { label: '节点聚合（纯链接，无分流规则）',
      formats: [
        { key: 'singbox',   name: '📦 Sing-box',      desc: 'Sing-box 原生格式' },
        { key: 'v2ray',     name: '📄 V2ray',         desc: 'V2ray 标准订阅 (Base64)' },
        { key: 'v2rayn',    name: '📱 V2RayNG',       desc: 'V2RayNG Android' },
        { key: 'nekoray',   name: '🪐 NekoRay',       desc: 'NekoRay / NekoBox' },
        { key: 'shadowrocket', name: '🚀 Shadowrocket', desc: 'Shadowrocket iOS' },
      ]},
  ];
  document.getElementById('outputLinks').innerHTML = groups.flatMap(g => {
    return [
      \`<div class="sub-group-label">\${g.label}</div>\`,
      ...g.formats.map(f => {
        const url = \`\${baseUrl}/\${f.key}/{key}\`;
        const dnsNote = f.key === 'mihomo'
          ? \`<div style="margin:6px 0 12px;padding:9px 12px;color:var(--red);font-size:13px;line-height:1.6;background:var(--bg);border-left:3px solid var(--red);border-radius:6px">⚠️ 防 DNS 泄露：用 <b>OpenClash</b> 导入本配置时，请到 插件面板 → 全局设置 → DNS 设置，<b>关闭「自定义上游 DNS 服务器」</b>——否则会覆盖本订阅的 DNS 分流，导致国内 DNS 地址明文外发（DNS Leak Test 报中国 IP）。</div>\`
          : '';
        return \`<div class="sub-item" onclick="showConfigModal('\${f.key}', '\${f.name}')">
          <span class="name">\${f.name}</span>
          <span class="desc">\${f.desc}</span>
          <input value="\${url}" readonly onclick="event.stopPropagation();this.select()">
          <span class="sub-actions">
            <button class="btn btn-sm" onclick="event.stopPropagation();showQrModal('\${f.key}', '\${f.name}')">📱 二维码</button>
            <button class="btn btn-sm" onclick="event.stopPropagation();copyFormatUrl('\${f.key}')">📋 复制</button>
          </span>
        </div>\${dnsNote}\`;
      }),
    ];
  }).join('');
  // 异步获取订阅 key 后替换占位符
  loadSubKey();
}

let subKey = '';
async function loadSubKey() {
  try {
    const data = await api('/sub-key');
    subKey = data.data?.key || '';
    if (subKey) {
      document.querySelectorAll('#outputLinks input').forEach(input => {
        input.value = input.value.replace('{key}', subKey);
      });
    } else {
      document.querySelectorAll('#outputLinks input').forEach(input => {
        input.value = input.value.replace('{key}', '');
      });
    }
  } catch (e) {
    // 认证过期或网络异常：保持占位符并提示
    document.querySelectorAll('#outputLinks input').forEach(input => {
      input.value = input.value.replace('{key}', '');
    });
    const container = document.querySelector('#outputLinks');
    if (container) {
      const el = document.createElement('div');
      el.style.cssText = 'color:var(--red);font-size:14px;margin-top:8px;padding:8px;background:var(--bg);border-radius:10px';
      el.textContent = '⚠️ 无法获取订阅链接，请重新登录';
      container.appendChild(el);
    }
  }
}

function copyFormatUrl(format) {
  copyText(\`\${window.location.origin}/sub/\${format}/\${subKey}\`, '已复制订阅链接');
}

// ============ 二维码 ============
function showQrModal(format, name) {
  const url = encodeURIComponent(\`\${window.location.origin}/sub/\${format}/\${subKey}\`);
  if (!subKey) { toast('尚未获取订阅密钥，请刷新重试', 'error'); return; }
  document.getElementById('qrContainer').innerHTML = \`<img src="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=\${url}" alt="QR码" style="border-radius:8px">\`;
  document.getElementById('qrFormatName').textContent = name + ' 订阅';
  showModal('qrModal');
}

function copyUrl(url) {
  copyText(url, '已复制');
}

function showConfigModal(format, name) {
  showModal('configModal');
  document.getElementById('previewFormatSelect').value = format;
  document.getElementById('configPreview').textContent = '加载中...';
  previewConfig(format);
}

function previewSelect(force) {
  const select = document.getElementById('previewFormatSelect');
  const format = select.value;
  // onchange 自动加载（点击行进入时也可能触发，force 仅语义化）
  void force;
  previewConfig(format);
}

async function previewConfig(format) {
  document.getElementById('configPreview').textContent = '加载中...';
  try {
    const res = await fetch(\`/api/output/\${format}\`, { credentials: 'include' });
    if (!res.ok) throw new Error('加载失败');
    const text = await res.text();
    document.getElementById('configPreview').textContent = text;
  } catch (e) {
    document.getElementById('configPreview').textContent = '加载失败: ' + e.message;
  }
}

async function downloadConfig(format, filename) {
  try {
    const res = await fetch(\`/api/output/\${format}\`, { credentials: 'include' });
    const blob = await res.blob();
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = filename; a.click();
    URL.revokeObjectURL(a.href);
    toast('下载完成');
  } catch { toast('下载失败', 'error'); }
}

/** 各格式对应的标准配置文件名后缀（客户端直接识别的文件名和类型） */
const CONFIG_FILE_NAMES = {
  mihomo:        'mihomo.yaml',
  singbox:       'sing-box.json',
  v2ray:         'v2ray.txt',
  v2rayn:        'v2rayn.txt',
  nekoray:       'nekoray.txt',
  shadowrocket:  'shadowrocket.txt',
};

/** 读取预览弹窗当前选中的格式，按客户端标准文件名下载 */
function downloadConfigByFormat() {
  const format = document.getElementById('previewFormatSelect').value;
  const filename = CONFIG_FILE_NAMES[format] || \`subscription.\${format}\`;
  downloadConfig(format, filename);
}

async function downloadMihomo() { downloadConfig('mihomo', 'mihomo.yaml'); }
async function downloadSingbox() { downloadConfig('singbox', 'sing-box.json'); }

// ============ 输出页主操作条（A：格式选择器驱动） ============
function getOutputFormat() {
  return document.getElementById('outputFormatSelect').value;
}

function copyOutputFormatUrl() {
  copyFormatUrl(getOutputFormat());
}

function downloadOutputFormat() {
  const format = getOutputFormat();
  const filename = CONFIG_FILE_NAMES[format] || \`subscription.\${format}\`;
  downloadConfig(format, filename);
}

function showQrOutputFormat() {
  showQrModal(getOutputFormat(), document.getElementById('outputFormatSelect').selectedOptions[0].textContent);
}

function previewOutputFormat() {
  showConfigModal(getOutputFormat(), document.getElementById('outputFormatSelect').selectedOptions[0].textContent);
}

function onOutputFormatChange() {
  // 预留：将来可联动刷新节点数或自动预加载
}

// ============ Settings ============
async function loadSettings() {
  try {
    const data = await api('/settings');
    document.getElementById('settingAppName').value = data.data?.app_name || '';
    document.getElementById('settingSubUpdateInterval').value = data.data?.sub_update_interval ?? 24;
    document.getElementById('settingNodeDropLatency').value = data.data?.node_drop_latency_ms ?? 2000;
  } catch {}
  loadCatalogStatus();
  searchCatalog(); // 默认显示前 100 个分类
}


async function saveSettings() {
  const appName = document.getElementById('settingAppName').value.trim();
  const intervalRaw = document.getElementById('settingSubUpdateInterval').value.trim();
  const subInterval = intervalRaw === '' ? 24 : parseInt(intervalRaw, 10);
  if (Number.isNaN(subInterval) || subInterval < 0 || subInterval > 24) { toast('自动更新间隔须为 0-24 的整数（0 = 不更新）', 'error'); return; }
  const dropRaw = document.getElementById('settingNodeDropLatency').value.trim();
  const dropLat = dropRaw === '' ? 2000 : parseInt(dropRaw, 10);
  if (Number.isNaN(dropLat) || dropLat < 100 || dropLat > 2000) { toast('慢节点抛弃阈值须为 100-2000 的整数（毫秒）', 'error'); return; }
  try {
    await api('/settings', { method: 'PUT', body: JSON.stringify({ app_name: appName, sub_update_interval: subInterval, node_drop_latency_ms: dropLat }) });
    toast('设置已保存');
    // 立即刷新页面标题
    document.getElementById('sidebarLogo').textContent = appName;
    document.getElementById('loginTitle').textContent = '🔐 ' + appName;
    document.title = appName;
  } catch (e) { toast('保存失败: ' + e.message, 'error'); }
}

// ============ 账号安全（用户名/密码） ============

async function loadCurrentUsername() {
  try {
    const res = await api('/auth/username');
    const el = document.getElementById('currentUsername');
    if (el) el.textContent = res.data?.username || 'admin';
  } catch {}
}

async function changeUsername() {
  const newUsername = document.getElementById('settingNewUsername').value.trim();
  const currentPassword = document.getElementById('settingUsernamePassword').value;
  if (!newUsername || !currentPassword) { toast('请填写新用户名和当前密码', 'error'); return; }
  try {
    await api('/auth/username', { method: 'POST', body: JSON.stringify({ currentPassword, newUsername }) });
    toast('用户名修改成功，下次登录使用新用户名');
    document.getElementById('settingNewUsername').value = '';
    document.getElementById('settingUsernamePassword').value = '';
    loadCurrentUsername();
  } catch (e) { toast('修改失败: ' + e.message, 'error'); }
}

async function changePassword() {
  const currentPassword = document.getElementById('settingOldPassword').value;
  const newPassword = document.getElementById('settingNewPassword').value;
  const confirm2 = document.getElementById('settingNewPassword2').value;
  if (!currentPassword || !newPassword) { toast('请填写旧密码和新密码', 'error'); return; }
  if (newPassword.length < 6) { toast('新密码至少6位', 'error'); return; }
  if (newPassword !== confirm2) { toast('两次输入的新密码不一致', 'error'); return; }
  try {
    await api('/auth/password', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) });
    toast('密码修改成功，请重新登录');
    setTimeout(() => location.reload(), 1200);
  } catch (e) { toast('修改失败: ' + e.message, 'error'); }
}

// ============ 规则库管理（设置页） ============

/** 加载目录状态（更新时间/总数） */
async function loadCatalogStatus() {
  try {
    const res = await api('/rules/catalog/meta');
    const meta = res.data?.meta || {};
    const statusEl = document.getElementById('catalogStatus');

    if (meta.status === 'never') {
      statusEl.innerHTML = '⚠️ 尚未同步过规则库，点击「立即刷新」开始同步';
      return;
    }

    const statusText = meta.status === 'stale' ? '🟡 数据过期' : '🟢 正常';
    const lastUpdate = meta.fetchedAt ? new Date(meta.fetchedAt).toLocaleString('zh-CN') : '未知';
    statusEl.innerHTML = \`
      <div style="display:flex;flex-wrap:wrap;gap:12px;font-size:14px">
        <span>\${statusText}</span>
        <span>上次更新: \${lastUpdate}</span>
        <span>分类总数: \${meta.total ?? 0}</span>
      </div>
      \${meta.lastError ? \`<div style="color:var(--red);font-size:14px;margin-top:4px">上次错误: \${escHtml(meta.lastError)}</div>\` : ''}
    \`;
  } catch {
    document.getElementById('catalogStatus').innerHTML = '❌ 加载规则库状态失败';
  }
}

/** 手动刷新规则库 */
async function refreshCatalog() {
  const btn = document.getElementById('catalogRefreshBtn');
  btn.disabled = true;
  btn.textContent = '⏳ 刷新中…';
  try {
    const res = await api('/rules/catalog/refresh', { method: 'POST' });
    if (res.success) {
      const removedCount = (res.data?.removed || []).length;
      toast(removedCount > 0 ? \`✅ 规则库刷新完成，本次移除 \${removedCount} 条失效规则\` : '✅ 规则库刷新完成');
      // 重新加载状态和搜索
      loadCatalogStatus();
      // 清空搜索缓存，下次搜索走新数据
      catalogAll = [];
      const searchEl = document.getElementById('catalogSearch');
      if (searchEl.value) debouncedSearchCatalog();
    } else {
      toast('❌ 刷新失败: ' + (res.error?.message || '未知错误'), 'error');
    }
  } catch (e) {
    toast('❌ 刷新失败: ' + e.message, 'error');
  } finally {
    btn.disabled = false;
    btn.textContent = '🔄 立即刷新';
  }
}

// ============ 规则库（设置页） ============
let catalogAll = [];      // 全量分类清单（实际条数以「共 N 个分类」为准，会随上游同步增长）
let catalogSearchTimer = null;
let catalogType = '';     // 当前分类筛选：'' | 'aggregate' | 'site' | 'tld'
let addRuleGroupOptions = []; // 目标分组下拉选项

/** 点击分类筛选 chip */
function setCatalogType(btn) {
  catalogType = btn.dataset.type || '';
  document.querySelectorAll('.catalog-chip').forEach(c => {
    c.classList.toggle('active', (c.dataset.type || '') === catalogType);
  });
  searchCatalog();
}

// 首次进入设置页时加载 catalog 和分组下拉（只加载一次，后续复用）
async function ensureCatalogLoaded() {
  try {
    if (catalogAll.length === 0) {
      const groupsRes = await api('/rules/groups');
      const groups = groupsRes.data?.groups || [];
      // 缓存分组下拉选项
      addRuleGroupOptions = groups.map(g => ({ key: g.key, name: g.icon + ' ' + g.name }));
      // 加载 catalog 元信息（数量）
      const catRes = await api('/rules/catalog?limit=1');
      const total = catRes.data?.meta?.total ?? 0;
      document.getElementById('catalogCount').textContent = total ? \`共 \${total} 个分类\` : '';
      // 预填分组下拉
      const sel = document.getElementById('addRuleGroup');
      sel.innerHTML = addRuleGroupOptions.map(o => \`<option value="\${escHtml(o.key)}">\${escHtml(o.name)}</option>\`).join('');
    }
  } catch { /* catalog 加载失败静默，搜索时会再尝试 */ }
}

function debouncedSearchCatalog() {
  clearTimeout(catalogSearchTimer);
  catalogSearchTimer = setTimeout(searchCatalog, 250);
}

async function searchCatalog() {
  const q = document.getElementById('catalogSearch').value.trim();
  const list = document.getElementById('catalogList');
  list.innerHTML = '<div style="color:var(--text2);padding:16px;text-align:center">⏳ 搜索中…</div>';
  try {
    const limit = q ? 200 : 200;
    const params = new URLSearchParams();
    if (catalogType) params.set('type', catalogType);
    if (q) params.set('q', q);
    params.set('limit', String(limit));
    const res = await api(\`/rules/catalog?\${params.toString()}\`);
    const items = res.data?.catalog || [];
    const total = res.data?.meta?.total || 0;
    // 更新各分类计数徽标（首次加载后也填充）
    const typeCounts = res.data?.meta?.typeCounts;
    if (typeCounts) {
      document.querySelectorAll('.catalog-chip-count').forEach(badge => {
        const key = badge.dataset.count;
        badge.textContent = typeCounts[key] ?? badge.textContent;
      });
    }
    if (items.length === 0) {
      list.innerHTML = \`<div style="color:var(--text2);padding:16px;text-align:center">\${q ? '未找到匹配的分类' : '暂无数据，请先同步规则库'}</div>\`;
      return;
    }
    list.innerHTML = items.map(it => \`
      <div class="catalog-item" data-id="\${escHtml(it.id)}" data-label="\${escHtml(it.label || it.id)}" style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;border-radius:8px" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background='transparent'">
        <div style="display:flex;align-items:center;gap:10px;min-width:0">
          <span style="font-weight:600">\${escHtml(it.id)}</span>
          <span style="color:var(--text2);font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\${escHtml(it.label || '')}</span>
          <span style="color:var(--text2);font-size:14px;background:var(--bg);padding:2px 8px;border-radius:20px">\${it.type}</span>
        </div>
        <button class="btn btn-sm add-rule-btn">➕ 加入</button>
      </div>\`).join('') +
      (total > items.length ? \`<div style="text-align:center;padding:12px"><button class="btn btn-sm" onclick="showAllCatalog()" id="showAllBtn">📋 显示全部 \${total} 个分类</button></div>\` : '');
    document.querySelectorAll('.add-rule-btn').forEach(btn => {
      btn.addEventListener('click', function() {
        const item = this.closest('.catalog-item');
        if (item) openAddRule(item.dataset.id || '', item.dataset.label || '');
      });
    });
  } catch { list.innerHTML = '<div style="color:var(--red);padding:16px;text-align:center">❌ 搜索失败</div>'; }
}

/** 显示全部 1899 个分类 */
async function showAllCatalog() {
  const btn = document.getElementById('showAllBtn');
  if (btn) { btn.disabled = true; btn.textContent = '⏳ 加载中…'; }
  try {
    const res = await api('/rules/catalog?limit=5000');
    const items = res.data?.catalog || [];
    document.getElementById('catalogList').innerHTML = items.map(it => \`
      <div class="catalog-item" data-id="\${escHtml(it.id)}" data-label="\${escHtml(it.label || it.id)}" style="display:flex;align-items:center;justify-content:space-between;padding:8px 12px;border-radius:8px" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background='transparent'">
        <div style="display:flex;align-items:center;gap:10px;min-width:0">
          <span style="font-weight:600">\${escHtml(it.id)}</span>
          <span style="color:var(--text2);font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">\${escHtml(it.label || '')}</span>
          <span style="color:var(--text2);font-size:14px;background:var(--bg);padding:2px 8px;border-radius:20px">\${it.type}</span>
        </div>
        <button class="btn btn-sm add-rule-btn">➕ 加入</button>
      </div>\`).join('');
    document.querySelectorAll('.add-rule-btn').forEach(btn => {
      btn.addEventListener('click', function() {
        const item = this.closest('.catalog-item');
        if (item) openAddRule(item.dataset.id || '', item.dataset.label || '');
      });
    });
  } catch { document.getElementById('catalogList').innerHTML = '<div style="color:var(--red);padding:16px;text-align:center">❌ 加载失败</div>'; }
}

function openAddRule(id, label) {
  document.getElementById('addRuleId').value = id;
  document.getElementById('addRuleLabel').value = label || id;
  const groupSel = document.getElementById('addRuleGroup');
  groupSel.value = 'other';
  document.getElementById('addRuleModal').classList.add('show');
}

async function confirmAddRule() {
  const id = document.getElementById('addRuleId').value.trim();
  const label = document.getElementById('addRuleLabel').value.trim() || id;
  const groupKey = document.getElementById('addRuleGroup').value;
  // 根据分组自动推断目标策略：广告拦截→REJECT，国内直连→DIRECT，其余→PROXY
  const target = groupKey === 'ads' ? 'REJECT' : groupKey === 'china-direct' ? 'DIRECT' : 'PROXY';
  if (!id) { toast('分类 ID 无效', 'error'); return; }
  try {
    await api('/rules/custom', {
      method: 'POST',
      body: JSON.stringify({ id, label, groupKey, target }),
    });
    toast('✅ 已加入规则库');
    // 新规则自动选中，随其所属组输出（v2.27.0：自定义规则勾选→立即生效）
    customSelected.add(id);
    saveRuleSelection();
    closeModal('addRuleModal');
    // 刷新规则页，让新规则出现在对应分组；并清空搜索框恢复初始态
    if (typeof RULE_GROUPS !== 'undefined') { RULE_GROUPS = []; }
    if (window.pageRules) { /* no-op */ }
  } catch (e) { toast('加入失败: ' + e.message, 'error'); }
}

async function deleteCustomRule(id) {
  if (!id) return;
  if (!confirm('确定要从分流规则中删除「' + id + '」吗？')) return;
  try {
    await api('/rules/custom/' + encodeURIComponent(id), { method: 'DELETE' });
    toast('✅ 已删除规则: ' + id);
    // 刷新规则页，移除该规则
    if (typeof RULE_GROUPS !== 'undefined') { RULE_GROUPS = []; }
    loadRules();
  } catch (e) { toast('删除失败: ' + e.message, 'error'); }
}

// ============ Utils ============
function escHtml(s) { return String(s).replace(/[&<>"']/g, function(m) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]; }); }

// ============ 项目信息 + 升级检测 ============
let metaLoaded = false;
async function loadMeta() {
  if (metaLoaded) return;
  metaLoaded = true;
  try {
    const metaRes = await api('/meta');
    const meta = metaRes.data?.meta || {};
    const appName = metaRes.data?.app_name || meta.name || 'SUB-Aggregation';
    const ver = meta.version || '-';
    // 同时更新 sidebar 和 login 页的版本号
    const av = document.getElementById('appVersion');
    if (av) av.textContent = ver;
    const lv = document.getElementById('loginVersion');
    if (lv) lv.textContent = ver;
    // 动态替换站点名称
    document.getElementById('sidebarLogo').textContent = appName;
    document.getElementById('loginTitle').textContent = '🔐 ' + appName;
    document.title = appName;
  } catch { /* 版本信息加载失败静默 */ }

  // 升级检测（静默，不阻塞页面）
  try {
    const upRes = await api('/meta/check-upgrade');
    const up = upRes.data || {};
    // 更新 sidebar 升级状态
    const elSidebar = document.getElementById('upgradeStatusSidebar');
    if (up.hasUpdate && up.latest && elSidebar) {
      elSidebar.innerHTML = '<span class="upgrade-banner" style="padding:2px 8px;font-size:14px">🆕 <a href="' + escHtml(up.releaseUrl || '') + '" target="_blank" rel="noopener">v' + escHtml(up.latest) + '</a></span>';
    }
  } catch { /* 升级检测失败忽略 */ }
}

// ============ Init ============
window.addEventListener('DOMContentLoaded', async () => {
  // 从 hash 恢复页面
  const savedPage = window.location.hash.replace('#', '') || 'dashboard';
  if (['dashboard','subscribe','nodes','rules','output','settings'].includes(savedPage)) {
    state.currentPage = savedPage;
  }
  loadMeta();
  // 5 秒硬性兜底：即使 checkSession 因网络问题既不 resolve 也不 reject（fetchWithTimeout 15s 兜底），
  // 也保证 switchPage 在 5s 内执行 → 永不白屏
  await Promise.race([
    checkSession(),
    new Promise(r => setTimeout(r, 5000)),
  ]);
  switchPage(state.currentPage);
});

window.addEventListener('hashchange', () => {
  const page = window.location.hash.replace('#', '') || 'dashboard';
  if (['dashboard','subscribe','nodes','rules','output','settings'].includes(page)) {
    switchPage(page);
  }
});
</script>
</body>
</html>`;
export default HTML;
